### ISSUE TITLE
WhatsApp code not working with KTL

### ISSUE THREAD

**Issue by MickGraham23** [cortexrd/Knack-Toolkit-Library#100]
Hi, I have a contact page with a whatsapp icon which is embeded from Knack into my website. 
However if I install the KTL in the Javascript section the Whatsapp icon doesnt work.

 //  

  (function () {
    var options = {
      whatsapp: "+447423520269", // WhatsApp number
      call_to_action: "Message me on WhatsApp", // Call to action
      position: "right", // Position may be 'right' or 'left'
    };
    var proto = document.location.protocol, host = "getbutton.io", url = proto + "//static." + host;
    var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
    s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
    var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
  })();

  // 

rgds Michael

**Comment by CharlesBrunelleIO** [comment]
Hi Michael,

Could you show me your whole Javascript code you put in Knack? Thanks.

Charles

**Comment by MickGraham23** [comment]
Thats all the code.   But as soon as the KTL_Loader.js is added it stops the whatsapp button.
You can see it without the KTL_Loader.js  at https://melicsolutions.co.uk/contact   The green button at bottom right will load. 
 :)

**Comment by cortexrd** [comment]
For your convenience, here's what your code should look like:

```
KnackInitAsync = function ($, callback) { // Load the Knack Toolkit Library (KTL)
    (window.LazyLoad = LazyLoad) && LazyLoad.js(['https://ctrnd.s3.amazonaws.com/Lib/KTL/KTL_Start.js'], () => {
        loadKtl($, callback, (typeof KnackApp === 'function' ? KnackApp : null), '' /*KTL version, leave blank to get latest*/, 'min'/*min or full*/);
    })
};


//Your app's version.
window.APP_VERSION = '1.0.0';

window.ktlReady = function (appInfo = {}) {
    var ktl = new Ktl($, appInfo);

    //KTL Setup - BEGIN
    ktl.scenes.setCfg({
        versionDisplayName: 'MyApp', //Short version of your app name. Leave empty to hide it. Comment whole line for actual app name.
    })

    ktl.core.setCfg({
        developerNames: ['Firstname Lastname'], //Add your name here to get super powers!

        //Main KTL feature switches.  Here is where your App can override the defaults and enable/disable the features.
        enabled: {
            //"Basic" features
            //Enabled by default. To disable them, their flag must exist and be set to false.
            versionInfo: {
                viShowAppInfo: true,
                viShowKtlInfo: true,
                viShowToRoles: ['Developer'], //Array of Account Roles strings who can see the version info bar. Leave empty for all.
                viPosX: 'right', //right, center, left
                viPosY: 'top', //top, bottom
                viPosXMobile: 'center', //right, center, left
                viPosYMobile: 'bottom', //top, bottom
                viOpacity: 50, //0 to 100
                viOpacityHover: 100, //0 to 100
            },

            showMenuInTitle: true,
            selTextOnFocus: true,
            inlineEditColor: true,
            rowHoverHighlight: true,
            chznBetter: true,
            autoFocus: true,
            sortedMenus: true,
            userFilters: true,
            persistentForm: true,
            calendarGotoDate: true,
            rememberMe: true,
            formPreValidation: true,
            spinnerWatchDog: true,
            idleWatchDog: true,
            debugWnd: true,
        },
    });
    //KTL Setup - END


    //KTL callbacks to your App - BEGIN
    //KTL callbacks to your App - END

    /////////////////////////////////////////////////
    //Your App-specific code goes here...


    //  <!-- GetButton.io widget -->

    (function () {
        var options = {
            whatsapp: "+447423520269", // WhatsApp number
            call_to_action: "Message me on WhatsApp", // Call to action
            position: "right", // Position may be 'right' or 'left'
        };
        var proto = document.location.protocol, host = "getbutton.io", url = proto + "//static." + host;
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
        s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();

    // <!-- /GetButton.io widget -->


    //The rest of your code has been left out, but should go here....


    // Show password on click of eye icon on login and registration forms
    $(document).on('knack-view-render.any', function (event, view, data) {
        //...
    })

}
```

**Comment by MickGraham23** [comment]
Hi Norm,
When the  //Your app's version.is installed, that’s when the WhatsApp Icon disappears.

Ill try switching things off and see if its one of those true/false options 😊

Regards

Sent from Mail for Windows

**Comment by MickGraham23** [comment]
Hi Norm,

That hasn’t worked for me and I have removed the //Your App’s section and the WhatsApp icon is back but my css is a bit strange on that contact page again even although I’ve cleared caches etc.

??

Rgds Michael

Sent from Mail for Windows

**Comment by cortexrd** [comment]
Micheal,

Can you give me access to a single "dummy" page for testing?  Nothing is needed in it.
Leave the KTL code there please.

Use this email for login:  nd@ctrnd.com
Send me the password at that email address, as well as the link.

Thanks,
Norm

**Comment by MickGraham23** [comment]
Hi Norm,

I see the problem is down to my website template.  I added the embed code into another site and it works perfectly.
WhatsApp come up correctly now. 

Thanks Again!

Regards Michael

Sent from Mail for Windows
