### ISSUE TITLE
_ha not working for .kn-tabkle-link

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#107]
Hi Norm

We think we have discovered an issue with the _ha keyword.  It doesn't align the headers for columns with .kn-table-link:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/db255b6b-e98f-46ee-8cd6-d197d32576c2)

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/bf03643a-5d75-42ab-a42b-1213eba730da)

Craig

**Comment by cortexrd** [comment]
Fixed in v0.15.19.
Good testing!  Thanks a lot.
Norm

**Comment by CSWinnall** [comment]
Thank you Norm this is great
