### ISSUE TITLE
Suggestion/question

### ISSUE THREAD

**Issue by Deanobeano2** [cortexrd/Knack-Toolkit-Library#109]
Hi Normand

Is it possible to toggle a hidden column on or off?

Kind regards
Dean

**Comment by cortexrd** [comment]
Hi Dean,

Yes it's possible and easy to do.

Add the `_hc` keyword to your view of choice with all the columns you want to hide/show, then add this code:


```
const MY_TOGGLE_COLUMNS_VISIBILITY_GRID = 'view_253';
$(document).on('knack-view-render.' + MY_TOGGLE_COLUMNS_VISIBILITY_GRID, function (event, view, data) {
    const gridViewButtonsDiv = document.createElement('div');
    gridViewButtonsDiv.setAttribute('id', 'gridViewBtnDiv');
    gridViewButtonsDiv.style.marginTop = '10px';
    gridViewButtonsDiv.style.marginBottom = '30px';

    const div = document.querySelector('#' + view.key);
    if (div) {
        div.prepend(gridViewButtonsDiv);
        var visible = false;
        var toggleColumnVisibilityBtn = ktl.fields.addButton(gridViewButtonsDiv, 'View Columns', '', ['kn-button', 'ktlButtonMargin']);
        toggleColumnVisibilityBtn.addEventListener('click', function (event) {
            if (visible) {
                toggleColumnVisibilityBtn.textContent = 'View Columns';
                $('#' + view.key + ' .ktlDisplayNone_tmpoff').addClass('ktlDisplayNone');
                $('#' + view.key + ' .ktlDisplayNone_tmpoff').removeClass('ktlDisplayNone_tmpoff');
            } else {
                toggleColumnVisibilityBtn.textContent = 'Hide Columns';
                $('#' + view.key + ' .ktlDisplayNone').addClass('ktlDisplayNone_tmpoff');
                $('#' + view.key + ' .ktlDisplayNone').removeClass('ktlDisplayNone');
            }
            visible = !visible;
        })
    }
})
```

Replace `MY_TOGGLE_COLUMNS_VISIBILITY_GRID` by your own view ID.

Enjoy,
Norm

**Comment by Deanobeano2** [comment]
Hi Norm

 

Thank you for that.

 

Unfortunately, we can’t seem to get it to work.  Also, when we add the Javascript code then the keywords such as _ha on other pages become visible.

 

We’ve attached our code, messy as it is sorry, for you to inspect in case of any clashes as Sunny recently wrote some code for a user in Australia and ourselves.

 

Kind regards

Dean Morrison

General Manager
Excell Cleaning Services Limited

**Comment by CSWinnall** [comment]
Hi Norm

This worked perfectly.

Thank You

**Comment by CSWinnall** [comment]
Hi @Deanobeano2 

Can you post your code in here and I'll see if I can help.  I can't see your attached code.

Craig

**Comment by cortexrd** [comment]
Dean,

I suspect that you might just have added the code at the wrong place and the call to functions that use the `ktl.fields.addButton` cause a crash.

Sorry, my bad.  I should have been more specific.

When I send code snippets like this one above, I usually mention that you must first read the instructions here:

https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Customizing-Features

This explains how you must copy the content of this file:
https://github.com/cortexrd/Knack-Toolkit-Library/blob/prod/KTL_Customization.js 
in your Javascript section, and insert the code in the `ktlReady` function at the end, just below:
`//Your App-specific code goes here...`
**Before** the last curly bracket.

Try that and let me know if that solves your issue.

Norm

**Comment by Deanobeano2** [comment]
Hi Norm

 

Thank you for the pointer as I’d just added it at the end of all the Javascript.

 

I’ve got it working now, thank you.

 

Kind regards

Dean Morrison

General Manager
Excell Cleaning Services Limited
