### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#111]
Hi Norm

I noticed you have added a feature for a virtual keyboard is there a flag somewhere I can turn this off with?

Craig

**Comment by cortexrd** [comment]
Yes, it's in progress.  I fixed you issue with a flag in core: **virtualKeyboard** and a condition that loads the code only for Linux devices with an ARM processor like the Raspberry PI 4.

So it shouldn't bother you anymore.

Norm

**Comment by CSWinnall** [comment]
Thank you Norm

Craig
