### ISSUE TITLE
Login screen not showing & app not loading

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#116]
Hi Norm,

We have an issue and so does @jbk68, when we go to our live app the login screen doesn't show and the following error is in console (our app is on ktl version 0.15.17):

<img width="513" alt="Screen Shot 2023-10-13 at 22 09 16" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/87712818-0866-4e49-a54b-6e1a4f4e8ab8">

On our new app we can login, we're using latest version this one.

Looks like a flag might be missing, we're having a go at fixing it now.

Thanks
Amanda

**Comment by CSWinnall** [comment]
Hi @cortexrd & @jbk68
We have updated our ktl on the app to 0.16.0 and this seems to have fixed it.  Not sure what has gone on but this should allow your app to run

Craig & Amanda

**Comment by jbk68** [comment]
I'm running 16.0 and still having issues, any other suggestions?

**Comment by jbk68** [comment]
Here is my first lines of KTL code.  Should I change the settings here?
![KTL](https://github.com/cortexrd/Knack-Toolkit-Library/assets/137515060/7cd62a88-0fb7-4e1f-aa57-44c9a19bab00)

**Comment by CSWinnall** [comment]
Hi @jbk68

Try replacing min with full but no I don't thin k its that.

Craig

**Comment by CSWinnall** [comment]
Hi @jbk68

We have put our app to specifically 0.16.0 so in the empty '' put that then try again
C

**Comment by jbk68** [comment]
You the man Craig, I changed 'min' to 'full" and instantly started working.  

I believe 'min' is the default setting so Norm may get overwhelmed with users like me that had default settings. 

Do you happen to know the difference between min and full or is there documentation that show the difference?

BTW, did you happen to try that code I put on Knack for the notes button?

Thanks again... JON

**Comment by CSWinnall** [comment]
Hi Norm

We have updated our KTL to 0.16.0 and made sure both our apps are on full not min.  When we were on 0.15.7 we got the error above. We also got the error when we were on 0.16.0 and min.  The latest version 0.16.1 (which doesn't seem to be on GitHub yet) also works.

Both our apps are working with no issues now.  If you need any further Info let us know as this is re-creatable at the moment.

Craig

**Comment by CSWinnall** [comment]
@jbk68 

0.16.1 which is the latest version works too.

Craig

**Comment by jbk68** [comment]
Norm, just to let you know, my login issues have been resolved.  However, my apps were using 16.0 and not working.  

With Craig's help and advise, I changed my settings from min to full and it started working again.

Thanks... JON

**Comment by cortexrd** [comment]
Guys, I'm terribly sorry about that.  I've mistakenly released a dev version that was incomplete.

We're now at 0.16.2 and it looks stable, even though there are still some bugs related to the automated drop down search when using a barcode scanner.  I am working on this now.

Norm
