### ISSUE TITLE
New Error when hovering over Version Info 

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#123]
HI Norm 

I'm on ver. 0.16.3.  When I hover over the info bar this error appears:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/cdfcaa9a-f868-4ac2-9fd4-4240a51d6b2d)

It points to this line of code:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/5bb92aef-ce00-4d2b-8dc3-83aff71a4566)

Craig

**Comment by cortexrd** [comment]
Craig,

Can't reproduce the bug.
Since it occurred with that crippled version with the bad deployment event, I won't spend time investigating this.  No one uses this one.

Norm

**Comment by CSWinnall** [comment]
Hi Norm

We are both having this issue again:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/229fd31c-859a-40cd-a3b0-e3abc001e549)


Craig

**Comment by CSWinnall** [comment]
Don't Worry I have found the issue in our ktl ready area for some reason it was commented out.
