### ISSUE TITLE
Bulk Edit error - date - dd-mm-yyy format

### ISSUE THREAD

**Issue by Deanobeano2** [cortexrd/Knack-Toolkit-Library#132]
Hi Guys

I ran across this error (?) on my 1st go while "dipping my toes in the water" with a bulk edit.
![Bulk Edit error - date - dd-mm-yyy format](https://github.com/cortexrd/Knack-Toolkit-Library/assets/130625963/7bcf6d1e-9c92-41bd-9be3-1b74e4495c8f)

I suspect it might be due to the less common date format we use here.

Dean

**Comment by cortexrd** [comment]
Possibly.  But still, the KTL should support all date/time formats without any user intervention.
We will investigate this and keep you updated.

Thanks for reporting,
Norm

**Comment by cortexrd** [comment]
Fixed.  Will show up in next release KTL v0.17.2 - later today.
Norm

**Comment by cortexrd** [comment]
**0.17.2** has been released.  You can test it now.
Norm

**Comment by Deanobeano2** [comment]
Hi Norm

 

That worked perfectly, now, thank you.

 

Kind regards

Dean Morrison

General Manager
Excell Cleaning Services Limited
