### ISSUE TITLE
Error when using ctrl+shift on an add an option form

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#137]
Hi Norm,

Getting an error when trying to use crtl + shift to view developer info popover, when on a add an option form. 

<img width="1257" alt="Screen Shot 2023-10-30 at 14 56 42" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/e62fd5c9-0c09-4476-8778-204f187c8afa">

Here I'm on a modal form, which opens from another modal form, when I add a new option to a connected field:

![Screen Shot 2023-10-30 at 14 56 53](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/bc56e7ce-5d8a-4aa8-b606-40b5f41b9864)

This is a very minor issue, the popover feature is amazing and spaces soooo much time.

Thanks
Amanda

**Comment by cortexrd** [comment]
Fixed in **KTL v0.17.2**
Thanks for reporting :)
Norm
