### ISSUE TITLE
Links to builder views from dev info popover always show table settings

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#138]
Hi Norn,

When following link to views in builder, from info dev popover, it always thinks the view type is a grid. This is a details view:

![Screen Shot 2023-10-31 at 10 11 21](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/0613d9c9-f517-43f6-b7bb-f9c35e6fdedd)

As you can see the URL has table at the end, rather than details

.../pages/scene_1454/views/view_3367/table
rather than
.../pages/scene_1454/views/view_3367/details

I just click out of the view and back in, which is still a hell of a look quicker than me searching round the backend for the view.

Thanks
Amanda

**Comment by cortexrd** [comment]
Will be fixed in next release KTL v0.17.3
Thanks for reporting!
Norm
