### ISSUE TITLE
Long click on view to refresh - issue when click dragging a scroll bars

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#139]
Hi Norm,

Me again, been testing out all the new ktl features, found an issue with the long click listener. If you try to drag a scrollbar it registers as as a long cick, refreshes the view and lands you at the start of the table again. See video:

https://www.loom.com/share/cbf9ba15c04d485c89f26c8fb669f90c?sid=40ca99e1-66d4-4f8c-b2ed-6ff1d1af40da

Love the obfs btw.

Thanks
Amanda

**Comment by amandajane-mo** [comment]
Hi Norm,

Is there a way (or could there be a way) we can turn this feature off for non devs? For now we've rolled back to version 16.4 for prod.

Thanks again,
Amanda

**Comment by amandajane-mo** [comment]
Hi Norm,

Click and a long press would work, less likely to do it by mistake and would allow users to click and drag.

Thanks
Amanda

**Comment by cortexrd** [comment]
I've released a **dev** version, please give it a try and let me know.
I find it working very well, personally.

ND

**Comment by amandajane-mo** [comment]
Hi Norm,

Works great, excellent. Also noticed that Craig's new keyword is live, we're very excited!

Thanks
Amanda
