### ISSUE TITLE
Dev Info popup not working correctly in modal forms

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#144]
Hi Norm,

Using KTL version 0.18.2, dev info popup not displaying view/scene info when in modal form, see screenshots:

![Screen Shot 2023-11-08 at 12 46 49](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/9b6c9500-89b8-4a8d-9081-29aea8797d68)

![Screen Shot 2023-11-08 at 12 47 09](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/044c5986-06cf-4e80-9735-3822e4045a58)

No errors in console. 

Thanks
Amanda

Note: screenshot of test client not actual client :)

**Comment by cortexrd** [comment]
Hi Amanda,

Good catch!  I was sure I fixed all of them.
Modals.... arghhhh!!!  Such a strange beast  LOL!!!

Will check this out shortly.

Thanks for reporting,
Norm

**Comment by cortexrd** [comment]
Fixed in v0.21.1.
Norm

**Comment by amandajane-mo** [comment]
Thanks Norm, this is amazing, works as expected. This is one of the ktl features I use the most, saves so much time.

Amanda
