### ISSUE TITLE
Inconsistency with persistent form in Rich Text fields when closing modal

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#146]
Hi Norm,

I've noticed an inconsistency with persistent forms, if I open a modal form, enter data in paragraph field and in rich text field, close out of the form and reopen, the data is re-entered into the paragraph field, but not the rich text field. 

Rich text persistence works in other scenarios, i.e. refreshing the page.

Thanks
Amanda

**Comment by cortexrd** [comment]
Amanda,

From what I can see, Charles has fixed this one working on some other fixes in Persistent Forms.
I tested and it looks ok here.

Let me know if I need to re-open,
Norm

**Comment by amandajane-mo** [comment]
Tested and working, many thanks
