### ISSUE TITLE
_cfv not working when field label format set to top 

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#151]
Hi Norm,

_cfv fails to work if label format set to top. Example:

`_cfv=[field_177, is, Admissions, , , ,r]`

Label set to left:
![Screen Shot 2023-11-13 at 14 25 11](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/1502ed86-3057-441e-b421-6e5e2519e22f)

Label set to top:
![Screen Shot 2023-11-13 at 14 25 57](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/e1c62d6c-3623-4b4c-8f72-7be9d9f5f735)

Thanks
Amanda

**Comment by cortexrd** [comment]
Amanda,

I am working on this - haven't forgotten about you!
It's just a bit more complicated than I thought...

Will get back soon,
Norm

**Comment by cortexrd** [comment]
Done, the fix is in **KTL v0.19.0**.
Can you test please?

Thanks,
Norm

**Comment by amandajane-mo** [comment]
Hi Norm,

Yep, all good, works as expected.

Thanks
Amanda
