### ISSUE TITLE
Error in toolkit code

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#152]
In one of my apps I am getting an error message and the app won't load. The error is in the last line in the code section below:
 title = attr.content.replace('<p>_', ' _');
 
 Error is:
 KTL-0.18.5.js:54 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
 
 It is not happening in my other apps just one specifically
 
 

//window.ktlParserStart = window.performance.now();
    //Parser step 1 : Add view keywords.
    //Extract all keywords from view titles and descriptions, and cleanup view titles and descriptions.
    var ktlKeywords = {};
    window.ktlKeywords = ktlKeywords;
    for (var t = 0; t < Knack.scenes.models.length; t++) {
        var scn = Knack.scenes.models[t];
        var views = scn.views;
        for (var v = 0; v < views.models.length; v++) {
            let view = views.models[v];
            if (view) {
                var viewKwObj = {};
                var attr = view.attributes;

                var title = attr.title;

                if (attr.type === 'rich_text')
                    title = attr.content.replace('<p>_', ' _');            (This line is the problem code)

**Comment by djbbiz** [comment]
Now getting another error:
Uncaught TypeError: Cannot read properties of undefined (reading 'includes')

Line 92 in my console:
 if (attr.type === 'rich_text' && !title.includes('_ol'))

**Comment by cortexrd** [comment]
I fixed that one in **v0.18.7**.

I'd really like to see what that **Rich Text** view contains.  Can you give me some info?
Or reproduce the bug in that App you shared me.

Norm

**Comment by cortexrd** [comment]
Hi Dean,

Do you still have the problem or should I close this?

Norm

**Comment by djbbiz** [comment]
Still have the issue will get you more info this week.

**Comment by cortexrd** [comment]
@djbbiz,

Any update on this one?

Norm

**Comment by cortexrd** [comment]
Dean, I will close this now.  Feel free to re-open if needed.

**Comment by djbbiz** [comment]
Sorry Norm, the app that is in isn't mission critical in its use of the KTL toolkit so I have not had a chance to return to it but do want to make it work. When I get back to it I will update you.
