### ISSUE TITLE
_uc question

### ISSUE THREAD

**Issue by imelcher** [cortexrd/Knack-Toolkit-Library#159]
Hi, 

First I would like to express my gratitude for this KTL. This makes the apps in Knack so much more useful. 
I am totally new here and have little to 0 coding experience. So I am hoping you can help here. 
Is there a way to make the name field force capitalization? I used the _uc in the table field but when I go to the form, it is not forcing the capital letter input. Also is it possible to do a Bulk Edit and make all the current name records capital letters?

**Comment by CSWinnall** [comment]
Hi @imelcher 

Can I just check is the _uc is in the field description in the data section of the builder.

Craig

**Comment by cortexrd** [comment]
Hi @imelcher,

Thanks for reporting this issue.  There was a bug indeed - good catch!
I've fixed it a minute ago and you will get it in next release, in a few hours today.
*** Just be sure you've subscribed to the **Changelog** discussion here:  https://github.com/cortexrd/Knack-Toolkit-Library/discussions/47 to know when it's done.

Norm

**Comment by imelcher** [comment]
Thank you so much Norm. 
It is working great!
