### ISSUE TITLE
Use of _bcg

### ISSUE THREAD

**Issue by Pwday** [cortexrd/Knack-Toolkit-Library#165]
Norm,
 Is there a way that the QR code could be stored for use in areas such as sending out emails with the code embedded?

**Comment by Pwday** [comment]
Norm it is OK I have worked out that the QR code needs to be an image field for the code to appear. I think this should be documented.
Thanks again

**Comment by Pwday** [comment]
So this is what I have found.

1. the h parameter does not hide the label
2. The field parameter is the field that you want to extract the data from and it uses the field content not the header
3. You need an additional field (image) on the view for you to load the QR image
4. The image is not persistent i.e, it is generated dynamically and not stored. It would be nice if it was stored so I could use it in sending out tickets via email, otherwise I have to print to PDF

Maybe a tutorial video :) for dummies like me would be good
Great library of tools!
Pete

**Comment by cortexrd** [comment]
I tried to implement this somehow, but without success.
The QR code image is generated on the screen only.  It's not even in the DOM, can't be copied to clipboard or save to disk in any way.  I was hoping to do an API call to store it in a field, but I can't grab the image in the first place.

I will ask Charles if he has some ideas.

How about a link in the email body that would open the QR code in a browser?  That may work, if it'd be an acceptable solution for you.

Norm

**Comment by Pwday** [comment]
Norm,

Thanks. It is OK If you ever produce a solution Ill implement 😊 I was going to use it to send emails that users could have the QR code imbedded to check in for a training session using the Knack QR application that is available. However, I can easily check them off the list directly in knack. Thank you for the effort in researching it and again for the great library of keywords.

Pete
