### ISSUE TITLE
Need Tooltips _ttip in action links also

### ISSUE THREAD

**Issue by cortexrd** [cortexrd/Knack-Toolkit-Library#172]
It would be beneficial to be able to use the tooltips keywords in views.  Currently it's only effective in fields.

This would allow using them with Action Links for example, where the outcome is not obvious and may need a bit more explanation.

If there's an overlap, i.e. being used in both the field and the view, then the view's should have precedence.

For for it Craig!!!

Norm

**Comment by CSWinnall** [comment]
Hi Norm I have been thinking about that as well so already on it.

Craig
