### ISSUE TITLE
In Line Edit Colour

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#179]
Hi Norm
Not sure if this is related to #173 or if you have already fixed this.  It made me think.

With the inlineEditColour turned on, if the column inline edit is turned on but the table is turned off the cell will still turn blue.  We have to turn the inline edit for the table on then turn each column off then turn the table back to off.

If you look at these 2 cells:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/32b08d44-f6f8-431e-ba14-2be72be94a44)

You can see that one has the column inline edit on and one has it off

The table has inline edit turned off:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/d57b143b-c658-447b-95ee-2210e9f06837)

I hope this makes sense: #173 made me think that this is an issue?

Craig

**Comment by cortexrd** [comment]
Very interesting. I think you've found something that may explain a few issues I've experienced with the KTL in the past.
Will check it out - thanks.
Norm

**Comment by cortexrd** [comment]
Should be fixed now.
Re-open is you see it again.
Norm
