### ISSUE TITLE
_LF Linked Filters issue: wont work if primary view is a chart

### ISSUE THREAD

**Issue by LeighBerrell** [cortexrd/Knack-Toolkit-Library#189]
Hi, I'm trying to use linked filters to drive a dashboard of graphs.  I find that if the first view (the one with the primary filter) is a Grid then all the cascading filters work, including those on my pie charts.  But if the first view is a Pie Chart, then no cascading filters work at all.  I seem to recall this was an original issue but was fixed long ago.  Has the issue arisen again?   Using current standard release.

**Comment by CharlesBrunelleIO** [comment]
[Feature / Reports Subview Keyword _lf #194](https://github.com/cortexrd/Knack-Toolkit-Library/pull/194)

The _lf now works on Charts. I brought this feature back. However, a chart cannot link to its own Report view or any specific charts inside or out. It can link only to other Report views, Table views and List views. If you want to link a chart to other charts, you must move the targeted charts outside the "master/source" chart's Report view.

Charles

**Comment by LeighBerrell** [comment]
Thanks Charles.  In the meantime I found a way to solve my immediate need that avoids the ongoing limitation mentioned above - as my first view on the dashboard page I created a 1-row grid view of the table that underlies all the following charts, and I set that up as my primary filter source, and use javascript to hide the actual grid element, leaving only the title and filter visible.  Works a treat.

<img width="482" alt="image" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/b5b61ec2-5f77-43a2-9b12-4bc5f574be26">

**Comment by LeighBerrell** [comment]
The only minor niggle is that the hidden grid "expands" slightly if I scroll the page down to see more charts below, which leaves an untidy gap between the filters and the first chart.  The code I'm using to hide that grid is below - if you know of a different way to hide that grid element that wont have this niggle I'd be grateful - I'm not a coder just a newbie, so any advise from a pro is always welcome.

$(document).on('knack-view-render.view_205', function (event, view, data) {
  $("table.kn-table").hide();
});

**Comment by LeighBerrell** [comment]
I just found the soln to my question.  It was the table wrapper element causing the issue.  This fixes it:

$(document).on('knack-view-render.view_205', function (event, view, data) {
  $("table.kn-table").hide();
  $(".kn-table-wrapper").hide();
});
