### ISSUE TITLE
Search not working properly following installation of the KTL basic LazyLoad

### ISSUE THREAD

**Issue by Deanobeano2** [cortexrd/Knack-Toolkit-Library#19]
Hi Norm/All

I've struck a problem after the initial installation of the KTL basic LazyLoad and testing a few flags. The issue only seems to manifest itself in 1 table/view which happens to be the only 1 I tested 2 or 3 flags on. If I search using only numbers all I get is the spinner but if the search contains letters only, or even 1 letter the search will perform as expected. The issue persists even after I've removed the KTL basic LazyLoad.

![image](https://user-images.githubusercontent.com/130625963/235103963-f4576750-aaa7-4a10-8e38-a2792df09283.png)
![image](https://user-images.githubusercontent.com/130625963/235104231-c7884082-e035-4e63-a43a-1a54126290ce.png)
![image](https://user-images.githubusercontent.com/130625963/235104426-3c5b7ac2-421f-4a70-89aa-669787cc4a5c.png)

The only other thing I've noticed is the following anomaly when I refresh the failed numbers only search.
![image](https://user-images.githubusercontent.com/130625963/235104772-9356d176-e092-4570-bf1e-bc99674df33a.png)

Regards
Dean

**Comment by cortexrd** [comment]
Hi Dean,

I'm not sure if this is related to the KTL.  Can you check the **logs** in the **console output** to see if there are any errors please?

You can do that by pressing **F12** (ot Ctrl+Shift+i) in Chrome/Edge/Firefox.  Then click on the console tab at top.  Ignore all X-Frame errors.

Norm

**Comment by Deanobeano2** [comment]
Hi Norm

 

It would appear that the issue isn’t related to KTL. It was a coincidence that a Knack bug occurred at the same time as I was testing KTL and in the 1 view that the bug manifested itself.

 

https://forums.knack.com/t/search-with-numeric-vs-alpha-characters/14171/7

 

Kind regards

Dean Morrison

General Manager
Excell Cleaning Services Limited
