### ISSUE TITLE
Switching Mode with out the KTL info bar

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#20]
Hi @cortexrd 

Is there a way to switch between modes without the info bar at the top of the page?  I seem to remember that you said to type ktlm() in the console.  That doesn't seem to work or am I remembering it wrong?

Craig

**Comment by cortexrd** [comment]
Hi Craig,

Nice to hear from you, hope all is going well with your development... with the KTL's fast **Dev or Hybrid** mode!

Currently, the only way to goggle is using the Version Info bar.  I used to have a global function ktltm() for "KTL Toggle Mode" that you could call from the console window.  That was in fact a shorter version of the full call to `ktl.core.toggleMode();`  I removed it to avoid the redundancy. If you need it, you can use the full version.

Actually, I think what I'll do is add a function **ktldo()** for "KTL Developer's Options"  that will show the new pop-up with all the dev options:

![image](https://user-images.githubusercontent.com/42851359/235458295-82dab703-2599-4a0b-ab35-720aaa587431.png)

Now from my experience, I strongly recommend that you leave the Version Info bar accessible somehow.  Sooner or later you'll need it or a user will need it for a punctual and individual debugging session.

If you don't want to see it you have several options:
1) make it invisible, by setting it opacity to zero (or around 10%) in onSceneRender:  `$('#verButtonId').css('opacity', '10%')`
2) display it only for those having the Developer role
3) set its position at the bottom of the page, where most users won't even notice it, combined with low opacity.

Norm

**Comment by CSWinnall** [comment]
Hi Norm

Great Thanks

Craig

**Comment by cortexrd** [comment]
Craig,

Here's something cool that I will add in the CSS file of the next KTL release:

```
#verButtonId:hover{
	opacity: 100% !important;
}
```

This way, if you decide to make the verButtonId invisible (or nearly), it will show up when you hover the mouse over it.

In the meantime, you can add the code in your CSS pane for now, until next release.

Norm

**Comment by CSWinnall** [comment]
Thank you Norm.

Kind regards,

Craig Winnall
07543423538
