### ISSUE TITLE
_nf at field level not working for me

### ISSUE THREAD

**Issue by LeighBerrell** [cortexrd/Knack-Toolkit-Library#202]
You must be getting sick of me by now.

I have tried to make the _nf (no filter) at field level work, with no success.  I have, for example, set up _nf the Auto increment field called Lead Index, on a table called Leads,  But it still appears as a filter option.  _nf works fine at view level, but not at field level.  And it is the same with prod or dev version selected.   Am I doing something wrong?

Here is the field in Builder
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/99598fdb-5a51-47bc-b40a-809a7c82c94d)

Here is the table in the app, before I click Add filters.  Note its latest KT:L version, but dev doesnt work either.
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/41da755f-0108-4c48-a689-38fb627d47ef)

And here is the filter popup offering this field as a filter option.
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/6ad9c928-47f9-4070-8fe3-60e9a11704d4)

**Comment by cortexrd** [comment]
> You must be getting sick of me by now.

LOL!!!  Not at all, quite the opposite.  You're contributing to making the KTL better - that's all.

Now it's very strange because no matter what I try, the _nf kw never fails here.  I tried Modal for example, because they're always in for a surprise.  But no, all is good.

Can you reproduce the issue in a public page, or one with a login for me?

Norm

**Comment by LeighBerrell** [comment]
Norm

https://berrell.knack.com/cooldrive#leads2/

if you go here you will access public pages with 2 grid views of the LEADS table.  This is all dummy data.  On that table I have marked 2 fields Lead Index and Lead Number with _nf in their description.  

The first tab "leads" has no view level _nf entry, so in theory its reliant on those field level _nf tags.  But I can still see those 2 fields as filter options.  i.e this is the issue Im reporting - the field level _nf tags appear ineffective.

The second tab provides the same view of the same table but added a view level entry _nf=Lead Index,Lead Number,Lead Reference for Display.  That view does remove those fields from filter options.

Note there are 3 fields being stripped in the view level NF - the extra one being "Lead Reference for Display".  This is important, because its a "test":   I also notice that once I have viewed the second table - the one with the view level NF setting that removes that extra field, if I return to the first page the filter restrictions from the second page are applied to it too.  I know its the view level filters because that third field is removed.   Are the view level NF setting supposed to be just for a specific view?  or they will apply to all views of that table?  Is this another separate issue?

rgds, Leigh

**Comment by cortexrd** [comment]
Leigh,

In view_338, can you add a column for the **Lead Index** field please?
The code needs to have that field in the table to operate properly.

You can hide it using the **_hc** kw, like this: **_hc=Lead Index**

Norm

**Comment by cortexrd** [comment]
You have an interesting use case.  It should be possible to disable filtering on a field that is not part of the grid.
I will meditate on this...
Norm

**Comment by LeighBerrell** [comment]
Ive added that lead Index column to both views and left it visible for now.

**Comment by LeighBerrell** [comment]
I also put the name for Lead Reference back to original just so its not confusing.

**Comment by LeighBerrell** [comment]
I see now that Lead Index has been removed from the filter options due to the _nf in the field.   
So I now understand that it works, for now, only if the field is in the grid.  Which sort of does go against my use case, as Im trying to remove things that I will likely never put in the grid - things that are never for display, and are only used for doing calculations or as a component of some other formula field.

**Comment by LeighBerrell** [comment]
But given it works at the view level, at least there is a current solution.

**Comment by cortexrd** [comment]
Good, that confirms what I thought.

So, I'll try to come up with a solution that works even when the filter parameter is not in the view.

Stay tuned,
Norm

**Comment by cortexrd** [comment]
Ok, this time I'm pretty sure I've got it.

The problem was: If the filter is set to **All fields in table**, I need to retrieve the fields from the **Object** instead of the View.

That's how it's done now.

Can you test the dev version please?

Norm

**Comment by LeighBerrell** [comment]
Dev version now appears to be working perfectly for both the view and field _nf options.
