### ISSUE TITLE
Bulk Edit not working on page with multiple tables

### ISSUE THREAD

**Issue by mitzvetsia** [cortexrd/Knack-Toolkit-Library#21]
Hi, 

I'm attempting to deploy your much appreciated resource on a page with multiple tables and can't seem to get it to work in this context. 

Is there a way to turn off the bulk edit table by table without turning off inline edit on that table?

**Comment by cortexrd** [comment]
Hi,

Currently, bulk operations are globally enabled.  But it would be easy to create a new keyword to disable each table individually.

How about this:
**_nbo=edit, copy, delete**

For **No Bulk Operation** = list of operations, separated by a comma.

Normand

**Comment by cortexrd** [comment]
Can you try it now please?  Refresh your browser's page to see the new code take effect.

For each view, you can add the **_nbo** keyword without parameter to disable all bulk ops.
You can also have **_nbo=edit, copy, delete** to disable each feature individually.

If this works, **please close the ticket** and spread the good news about the KTL in the Knack Forums!

Normand

**Comment by mitzvetsia** [comment]
![Screenshot 2023-05-09 at 2 26 18 PM](https://github.com/cortexrd/Knack-Toolkit-Library/assets/35780481/90a82395-39ea-444c-ad8e-36b856d124a8)
_nbo is working brilliantly to hide the checkboxes! 

...but... the bulk edit feature still doesn't seem to be working on this page of mine. Works just fine on a simple page I have with only one grid... but this over one with 4 tables/grids it isn't working at all on. 

Still happy to spread the word - lots of great features and amazing of you to share and be so responsive!

**Comment by mitzvetsia** [comment]
I've added you as a temp user with access to the one set of records I'm working with: 

[Go here to login
](https://scwinstallation.knack.com/installationservices#team-calendar/edit-client/64590a8037ed58002a158297/site-dashboard/64590ab073af1b002843d6a2/as-builts/64590ab073af1b002843d6a2/)
PW: %P&opn8@tx19
User Name: nd@ctrnd.com

I've used _nbo to disable the bulk feature on the other tables, leaving it only on the top table.  

When I attempt to make a "bulk edit" update on the top table it looks like it's going to work (I get the dialogue boxes about edits being made to so many records etc), but then no update is made. 

Super appreciate your time let me know what else I can provide you!

best,
Micah

**Comment by mitzvetsia** [comment]
realized I may not have answered all of your questions. 

1. inline edit IS turned on and I've confirmed I can edit fields 
2. first table is the one I left the bulk edit on (i.e. didn't apply _nbo) and it didn't help
3. I've already been focusing on the top grid. 

Also not working on other pages where I have not applied _nbo, so doesn't appear to be related to that. 

I don't have any other custom JS or even CSS running on these particular pages....

**Comment by cortexrd** [comment]
Hi Mitz (?),

I can reproduce the problem in your app and also in one of my many apps.  The bug is related to the fact that sometimes, a GET API call won't return anything whereas it should.

This simple code proves it easily:

```
const sceneKey = Knack.router.current_scene_key;
const viewId = document.querySelector('.kn-table.kn-view').id;
const recId = document.querySelector('#' + viewId + ' .kn-table-table tbody tr').id;//'64591cd9478631002817726d';
console.log('viewId =', viewId);
console.log('recId =', recId);


var apiURL = 'https://api.knack.com/v1/pages/' + sceneKey + '/views/' + viewId + '/records/' + recId;
$.ajax({
    url: apiURL,
    type: 'GET',
    headers: {
        'Authorization': Knack.getUserToken(),
        'X-Knack-Application-Id': Knack.application_id,
        'X-Knack-REST-API-Key': 'knack',
        'Content-Type': 'application/json',
    },
    success: function (data) {
        console.log('data =', data);
    },
    error: function (response) {
        console.log('error', response);
    },
});

```

If you can try it yourself: just copy/paste this code in your console (F12) in a page that has at least one table with data.  Any app and any page is a good test.  If it works properly, you will see the returned record, being the first row of the first table found.  If it fails, will show **records: []** (an empty array of zero length).

In my case, it works well maybe 75% of the time, and can vary even within the same app, differing from page to page.

I will raise a ticket with Knack about this.
In the meantime, I think I may have a solution to get around this, and it may be even better, requiring one less API call.

Will keep you informed,
Norm

**Comment by mitzvetsia** [comment]
Hi Norm, 

Brilliant. I see exactly the behavior you're describing. I get an empty array on the page where the bulk edit isn't working and a populated array on the page where it does. 

I'll stay tuned and I appreciate your work on this so much! 

-Micah

**Comment by cortexrd** [comment]
I've also added a post on Knack's forum: [https://forums.knack.com/t/api-calls-with-a-get-command-returns-empty-records/14231](url)

**Comment by mitzvetsia** [comment]
Please, feel free to share with Knack support! 

Yes, that is in fact me, nice to meet you as well. That instagram is a bit of a throwback. lol. 

-Micah

**Comment by cortexrd** [comment]
Hi Micah,

I got my answer from Knack yesterday.  It's a bit more complicated than I thought, but indeed, there's a real problem. It's not a bug though, just something that's not obvious and not well documented, about using the Knack API with a GET command.

All this to say that I know how to fix the problem, and will do it next week, probably Monday or Tuesday.

Will keep you informed

Cheers, have a nice weekend,
Norm :)

**Comment by mitzvetsia** [comment]
Fixed! Huge thanks!
