### ISSUE TITLE
Some Fields not allowing Inline Edit in Grid View

### ISSUE THREAD

**Issue by Greenlight88** [cortexrd/Knack-Toolkit-Library#210]
Hi Norm,

Issue cropped up last couple of days - I bypassed the KTL and this resolved the issue.

A column that has inline edit allowed for the role wont allow changing the value - it will bring up the selector and let you select a different option but the submit button is washed out wont let you update it to any different value

Doesn'tseem to have a pattern of just applying to some field types - I believe issue may be with rules that are set on the grid at the column level for each field

I've tried deleting these rules for that column but that didn't resolve the issue - I believe it may relate to rules that refer to that column?

Its entirely possible that Ive set these up in a way that KTL doesn'tlike and problem is unique to me

This view for example - 

https://greenlightservices.knack.com/greenlight-online#enquiries4/proposals-to-prep2/?view_3855_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_1820%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22Ready%20to%20Check%22%2C%22field_name%22%3A%22Proposal%20Status%22%7D%5D%7D&view_3855_search=&view_3855_page=1

A Proposal Reviewer should be able to change the column 'State'

I have given your account this role just now

**Comment by cortexrd** [comment]
I've just fixed that bug a few minutes ago.
Update to  **v0.22.10** please.

Let me know if you still have the issue,
Norm
