### ISSUE TITLE
Possible Issue with Bulk Edit - File Fields

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#211]
Hi Norm, 

As I'm a newbie I'm not sure if its something I'm doing wrong or whether I've found an issue with the bulk edit not working on file fields?
https://www.loom.com/share/aa561424cc9e4984b97dae163e2a29b0?sid=3c641e3f-fd46-4230-8d05-8a096cdc303f

**Comment by cortexrd** [comment]
You're right Carl!  File type is not supported with the API.
I have removed the checkboxes for those, so we can't select them anymore.

Thanks for reporting,
Norm
