### ISSUE TITLE
Error With _cls ktlTarget is undefined 0.22.12

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#214]
Hi Norm

We are getting this error when calling _cls without a ktlTarget:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/12f81cfe-5100-4020-9666-8f78fc6d0315)

_cls=[border-top]

It points to this line in addRemoveClass:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/963c462e-4012-49fe-8ad3-38182c2a2d11)

In this area of code:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/8a603ae7-8756-4781-b534-cb4534ee8b68)

We are on version 0.22.12 it is not an issue on 0.22.10

Thanks Craig

**Comment by cortexrd** [comment]
I pushed a fix and uploaded the dev version, if you want to try it out.
Norm

**Comment by CSWinnall** [comment]
Thank you I'll test in the morning.
