### ISSUE TITLE
Issue with ktlTarget using jQuery containing square brackets 

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#220]
Hi Norm

This is a fix until we update our Prod KTL 0.22.14.

I have added the below keyword instead of _ro temporarily: 

`_style=[display: none], [ktlTarget, $("#view_3091-field_4707 option[value='Extra Info']")]`

Now I cannot see an error in the keyword above and it is working as expected, but this is in the console:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/c11b1d1c-95ff-4df2-a244-c67b2e4890cc)

Any thoughts?

Craig

**Comment by CSWinnall** [comment]
Hi @cortexrd 

After some investigation the issue is the `option[value="Extra Info"] `, I believe this is due to the square brackets in the Jquery selector?

Craig

**Comment by cortexrd** [comment]
You're right Craig, good catch.

The parser gets confused due to the conflict between the square brackets of the Group delimiters and those of the jQuery selector.

I will need to add some extra logic to detect and address this use case.

Norm

**Comment by CSWinnall** [comment]
Thank you it's a fringe case and has been replaced with the _ro keyword so it's not in use anymore.

Craig
