### ISSUE TITLE
_cmr In Promise error when updating all views

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#223]
Hi @cortexrd 

We have found an issue when using _cmr with no params.  The gist is that we have a page with multiple forms that we show hide certain forms depending on the record that we clicked to edit.  We also link to this modal from different pages too.

**To recreate the issue**

- Add 2 grids to 2 different pages both showing the same source
- Filter grid 1 by a type of record (e.g Audit Name is Fire Alarm Test0
- Filter grid 2 by a type of record (e.g. Audit Name is Fire Door Inspection)
- Add an edit record action to grid 1 then link to that page from grid 2
- Add 2 forms (e.g. 1 updates Audit Fire Alarm Test, 2 updates Fire Door Inspection Audit)
- Using page rules hide form 2 if you click on the edit in grid 1
- Using page rules hide form 1 if you click on edit link in grid 2 (e.g. Hide Form 1 if Audit Name is not Fire Alarm Test Audit )
- Add _cmr to both forms with no parameters

When you submit either form we get an in promise error because cmr can't find one of the grids

We have fixed this for now by being specific with our views i.e. `_cmr=view_5067`

Hope this makes sense
Craig

**Comment by cortexrd** [comment]
I didn't try to reproduce your setup, but I fixed a bug related to _cmr that closely relates to some parts of your description. Depending on where you called the modal, the parent wasn't always the one I was assuming.

See the _cmr code, just below this line:  **//All parent views.**

You'll understand.

And let me know if any magic it solved your issue, or there's something else to address.

Norm

**Comment by CSWinnall** [comment]
Hi Norm

I saw you changes and I think you are on the right lines with this one.  I'll test tomorrow.

Thank you 

Craig

**Comment by CSWinnall** [comment]
All good thanks
