### ISSUE TITLE
Debug Error

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#227]
Hi Norm,

We're having an issue with debug, as is Carl. When we switch to debug the page won't load and this error appears in the console:

<img width="1143" alt="Screen Shot 2024-02-09 at 10 15 05" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/c95dcb25-7ec5-4834-a5b6-20e1c66259c4">

We had to clear local storage (remoteDev) to fix the issue.

Thanks
Amanda

**Comment by chprojectsupport** [comment]
Very thankful to Craig and Amanda for their assistance in getting my app working again as I have a live demo in just over an hour 🙏

**Comment by cortexrd** [comment]
HI guys,

I was desperately trying to get my main app at Morbern to get back on its feet last night.  It was completely dead for several hours.  So I was experimenting with some dev code.

I've put back the normal code.

Give it a try please.

Norm

**Comment by chprojectsupport** [comment]
Ouch, what happened that rendered the Knack application dead for several hours 😲

**Comment by cortexrd** [comment]
Not too sure, their explanation is vague and refers to an old bug that they've now fixed.
All I know is that the KTL parser was crashing because it encountered **undefined** fields in an object.

FYI, even the Builder was completely dead.

All this lasted from 6:00pm to 8:30pm.

Norm
