### ISSUE TITLE
Pause Auto Refresh - Search Compoents

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#229]
Hi Norm, 

As you can see from below, I'm having an issue with Pause Auto Refresh not working on search components. I've tried on one of my other client apps and I get the same result. The pause is ignored and the auto refresh is reloading the whole component.

[https://www.loom.com/share/6ed48bbff53d4eb4982d3111f711b828?sid=ee26e60b-f4e7-463c-b853-54bbf905c40f](url)

[https://www.loom.com/share/a04e95ce83024b57889daa235b91b767?sid=13965d63-5341-4972-856b-0ac1e344ccf0](url)

**Comment by cortexrd** [comment]
Hi Carl,

That's strange.  I tested here and it works as expected.
A Search view with _ar=5 and _ts.  When I click Pause Auto-Refresh (at top-center of page) all stops.

BTW, your links seem to be broken.

Norm

**Comment by cortexrd** [comment]
I can debug in Zoom if you want.
I'm available now.

**Comment by chprojectsupport** [comment]
I’ve just sent you the Loom links via Slack. I’m using the same keywords as you and it doesn’t work in Travis app or another one of mine that I tested it in. 🤷‍♂️Carl HolmesOn 10 Feb 2024, at 17:35, Cortex R&D Inc. ***@***.***> wrote:﻿
Hi Carl,
That's strange.  I tested here and it works as expected.
A Search view with _ar=5 and _ts.  When I click Pause Auto-Refresh (at top-center of page) all stops.
BTW, your links seem to be broken.
Norm

**Comment by cortexrd** [comment]
Carl,

I guess we can close this one?

Norm

**Comment by chprojectsupport** [comment]
Yes, thank you, you have resolved the issue with auto pause not working on
a search component 👍

Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com
