### ISSUE TITLE
Interferes with column layout -- causes last column to be offset/missing

### ISSUE THREAD

**Issue by mitzvetsia** [cortexrd/Knack-Toolkit-Library#23]
![Screenshot 2023-05-18 at 11 13 30 AM](https://github.com/cortexrd/Knack-Toolkit-Library/assets/35780481/fabb81c7-a7f8-4957-9cc1-c70c42713b56)

 ^ Page with the library is turned one. (the first one IS a table, there's just a ton of CSS in place)

Same page, library commented out: 

![Screenshot 2023-05-18 at 11 15 51 AM](https://github.com/cortexrd/Knack-Toolkit-Library/assets/35780481/51eae6f1-f554-49ba-bfe2-783e1bd8bd2e)

I suspect it has to do with the version just pushed out -- 0.11.11

When I pull 0.11.9 instead, I don't have this issue. 

best!
Micah

**Comment by mitzvetsia** [comment]
realized it might be helpful to now that the pieces that are missing are the summary row, behind all the CSS

**Comment by cortexrd** [comment]
Micah,

Can you send me an email with some temporary login info to access that page or a similar one please?
At **nd@ctrnd.com**

The previous one does not work anymore.

Norm

**Comment by mitzvetsia** [comment]
The page isn't behind any logins because it's a customer facing proposal, should have thought to include that! 

https://scwinstallation.knack.com/installationservices#all-quotes/new-proposal/6099745438b4de001b1995cb/

Here's the grid in the builder 

![Screenshot 2023-05-18 at 2 27 05 PM](https://github.com/cortexrd/Knack-Toolkit-Library/assets/35780481/d413f0df-2058-403f-933d-41d5271b1b17)

Here's the bulk of the CSS involved in transformation that section: 

`/*Cameras*/

#view_2266 > div.view-header {margin-bottom: 20px !important; margin-top: 20px !important; }
#view_2266 > div.kn-table-wrapper > table > tbody > tr:last-child {margin: 100px !important; }
#view_2266 > div.kn-table-wrapper > table > tbody > tr > td {padding: 2px !important; border: 0px !important; }
#view_2266 > div.kn-records-nav > div:nth-child(2) {margin: 0px !important;}
#view_2266 > div.kn-records-nav > div:nth-child(3) {margin: 0px !important;}
#view_2266 > div.kn-records-nav > div:nth-child(3) > div.level-left > div.kn-entries-summary {visibility: hidden; }

/*hidden camera fiels*/
#kn-scene_828 .field_74 {display: none;}
#kn-scene_828 .field_146 {display: none;}
#kn-scene_828 .field_173 {display: none;}
#kn-scene_828 .field_76 {display: none;}


/* grand total row of each section */
#view_2266 > div.kn-table-wrapper > table > tbody > tr:last-child > td {visibility: hidden !important; }
#view_2266 > div.kn-table-wrapper > table > tbody > tr:last-child > td {font-size: 1px; !important} 
#view_2266 > div.kn-table-wrapper > table > thead > tr {display: none;}
#view_2266 > div.kn-table-wrapper > table > tbody > tr:nth-child(10) {margin-top: 10px !important;}

#view_2266 > div.kn-records-nav > div.level > div.level-left > div.kn-entries-summary {visibility:hidden;}


/*END CAMERAS*/`

Thanks again!

**Comment by cortexrd** [comment]
Micah,

I think I nailed it.  All these scenarios with Groupings and Summaries are very complex to handle, so there may be some residual bugs.  I will ask you to be a bit patient, if you encounter more!  But you definitely helped me find a new special case, and it was pretty easy to fix this time.

You can switch to KTL v0.11.12 and let me know if it's ok.  Test with other tables, with different configs, just to be sure.
Then, close the issue - you're now good at this!

Cheers,
Normand

**Comment by mitzvetsia** [comment]
beautiful! 

I would not be surprised to be told that my use of Knack is stretching it's intended use case a little. We've got some complex business operations running through it. 

Thank you!!
