### ISSUE TITLE
_nsg not listed in keyword wiki

### ISSUE THREAD

**Issue by LeighBerrell** [cortexrd/Knack-Toolkit-Library#230]
Just pointing out that the _dnd keyword wiki says to apply the _nsg keyword as well, but I note that _nsg is not listed as a keyword, so maybe that has been missed by accident?

**Comment by CSWinnall** [comment]
Hi @LeighBerrell 

The wiki does have _nsg.

If you go to this link, you will see the keyword.

https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Keywords#_nsg

Craig
