### ISSUE TITLE
_footer displaying "undefined"

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#234]
Hi Norm, hopefully the below Loom link is valid so you can see the issue with _footer
https://www.loom.com/share/b0fda5cb331f4d5aa7a78be629fce2c3?sid=72366955-b8da-4dc1-b971-dfeb0986cb5b

**Comment by CSWinnall** [comment]
@cortexrd 

If you change this line of code
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/84e8a618-e184-42a9-a5bd-27857a5728b1)

On my app to this:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/3e6e6947-19b0-439c-a3cd-c421d58ca74f)

This will vary from app to app but it works for this specific app by changing the 0 to 2.

Hope this helps

Craig

**Comment by cortexrd** [comment]
Oh geez!!!  The documentation is not clear enough.

I meant to create a new page with **only** a Rich Text in it, then THIS view will become the footer across the app, in all pages.
You don't need to add the footer manually to each page.  This would defeat the purpose!

Give it a try,
Norm

**Comment by cortexrd** [comment]
Closing this now.  Craig said he made it work.
If you see anything else, just re-open.

Norm

**Comment by CSWinnall** [comment]
@chprojectsupport 
Yes I got this to work Norm has updated the wiki to reflect that the rich text needs to be in it's own page.

It can be behind a login if you want.

Craig

**Comment by chprojectsupport** [comment]
I'm on version 0.23.1 and still get "undefined" on the bottom of the page.
![2024-02-13_22-11-16](https://github.com/cortexrd/Knack-Toolkit-Library/assets/130801992/9aa408b9-f080-4da2-8439-e869a2266ee1)

**Comment by cortexrd** [comment]
Did you remove the **_footer** keyword in that page?  It shouldn't be there.  Only in the footer rich text view.
ND

**Comment by chprojectsupport** [comment]
I wasn't aware of the change on the wiki. Now that I have followed the new
instructions the footer works as expected 😊
Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com

**Comment by cortexrd** [comment]
> I wasn't aware of the change on the wiki.

Oops, I admit this hasn't been broadcast as it should.  I said _I'll do it_, but then forgot to say _It's done_ !!!

I need to remember this next time(s)...

Norm
