### ISSUE TITLE
_dtp intermitant filter removal issue

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#235]
Hi Norm, please see the below video explainer.
https://www.loom.com/share/d9b33696596f4935ba58a7a042258c4b?sid=61ac7680-8efb-4374-a505-266e439fced4

**Comment by cortexrd** [comment]
Carl,

I've done a lot of rework and bug fixes in the _dtp keyword.
Please give it a try in v0.23.7 and let me know how it goes.

Norm

**Comment by chprojectsupport** [comment]
I tried it this afternoon and it looks and works great. 👍Carl HolmesOn 18 Feb 2024, at 16:40, Cortex R&D Inc. ***@***.***> wrote:﻿
Carl,
I've done a lot of rework and bug fixes in the _dtp keyword.
Please give it a try in v0.23.7 and let me know how it goes.
Norm
