### ISSUE TITLE
Infinite Loading on Forms

### ISSUE THREAD

**Issue by AnthonyF96** [cortexrd/Knack-Toolkit-Library#237]
I don't know if this is mainly a KTL Issue; however, it was resolved once I removed KTL from the website. When submitting forms, it would get stuck in the 'Connecting' countdown that Knack generates. The form would then reload and show as blank (not following the redirect I have setup). The form would still submit the information - but wouldn't inform the end user as usual.

**Comment by AnthonyF96** [comment]
This is what appears in the error console of Edge - KTL's getPublicIP failed.  Make sure uBlock not active.

**Comment by CSWinnall** [comment]
Hi @AnthonyF96 

I would suggest you put a version number in the loader 0.22.20 until Norm has fixed the issue:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/530fd773-4e61-4a5f-b2da-6397e0499a3b)
Craig

**Comment by cortexrd** [comment]
@AnthonyF96 

A hot fix has been released a few minutes ago.
It addresses this issue.

Update to **KTL v0.23.5** please.

Norm
