### ISSUE TITLE
_dtp Only appears on 1 view in the page

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#238]
Hi Norm

I have added _dtp to 2 tables in one scene.  The fields added seem to load on the last view that renders.  I can't get the date time picker on more than one view.

Craig

**Comment by CSWinnall** [comment]
Amanda and I are also getting this error when trying to use the dtp

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/51cce5a6-78c6-452b-9d39-c8e606c53173)

We have added it to 1 view in the scene which has 3 views using the same data source and 2 menu views.

We are running KTL 0.23.0

Craig

**Comment by cortexrd** [comment]
Fixed in **v0.23.6**
Just released.

Norm
