### ISSUE TITLE
Inline Editing not working in grids

### ISSUE THREAD

**Issue by JulianKirkness** [cortexrd/Knack-Toolkit-Library#239]
I have added the KTL to a client's project and their inline editing in grids is no longer working. The popup has two submit buttons none of which work. See Image...
![Screenshot 2024-02-14 at 10 22 56](https://github.com/cortexrd/Knack-Toolkit-Library/assets/160014097/7b0a4440-b364-4d93-a471-844350c1ed4e)

**Comment by CSWinnall** [comment]
Hi @JulianKirkness 

Could you tell me what version of KTL you are using?

Craig

**Comment by cortexrd** [comment]
Hi Julian,

Nice to meet you.  I wish our first conversation would happen in a better context.  Really sorry for all that.

I spent from 12am to 2am trying to figure it out, but I don't have the bug here.  V0.23.3.  Very strange.

If someone can share his app or a dummy form that has the bug, it would be ideal.

Norm

**Comment by cortexrd** [comment]
@JulianKirkness 

I found the bug.
You can try **v0.23.5**

Norm

**Comment by cortexrd** [comment]
Julian,

I'll close the ticket.  If you see anything else, feel free to re-open it.

Thanks for reporting this,
Norm

**Comment by JulianKirkness** [comment]
Norm - Thanks for the quick response!

My client has had another issue today which they are concerned may be due to the KTL - shortly after commenting the KTL code out, their drop down menus unravelled apparently at random - in other words a load of pages became detached from the menus and appeared independently on the menu (there were 6 or 7 rows of items on the menu). 

Can you conceive of any circumstance in which these could be linked issues - or do you think the menu issue is more likely to be a Knack one (I have reported it to them)?

Julian

**Comment by cortexrd** [comment]
That's a new one. Never seen this before.

If they commented-out the loader, I can hardly see how the KTL could be related to this.
Tell them to force a full reload of the page with **Ctrl+F5** just to be extra sure.

And maybe get a screen grab so I can better visualize.

I am now leaving for the rest of the day, but I'll be reading the posts.  Maybe reply if I have something _meaningful_ to say.

TTYL,
Norm

**Comment by JulianKirkness** [comment]
Hi Norm

I suspect this is most likely a Knack issue - probably just a coincidence that it happened as we had an issue with the KTL - but I am hoping Knack can answer that. In the meantime, the client is a bit worried to put it back on

Julian

**Comment by cortexrd** [comment]
Hi Julian,

About the detached menu issue, is it still occurring, or was it a one-time event?

_>In the meantime, the client is a bit worried to put it back on_

I certainly understand that.  I'd feel the same too.

But if you **lock** the KTL to a given version that has been proven to work and is stable, there won't be problems.  It's only for the "bleeding edge" versions that it's a bit more risky.

I am currently elaborating a strategy to implement **Beta** testing by volunteer users.

This means that, when I want to push a new release, I will make it available as a Beta version that users can switch to (similar to the Dev version) and test all they can.  Once approved - and only then - I will do the official release.

Currently, the option is to stay on the _before-latest_ version for a while, test the latest code on a _low-risk_ or fake app.  And update after a few days or weeks.

Norm

**Comment by JulianKirkness** [comment]
Hi

I hadn't specified a version - which I guess I should do before turning it back on - need to read your docs a bit more first!

The menu thing was a one off - no idea how it happened but I hope Knack can figure it out.

Julian

**Comment by cortexrd** [comment]
>need to read your docs a bit more first!

LOL!!!  That's a  classic.  Don't worry, I've seen that so many times with new KTL users.  The documentation can be so overwhelming at first.

As they say:  **RTFM**... ------========>>>>> Read the _Fantastic_ Manual !!!

About the version lock, you may have found the information, but I add it for your convenience, if you haven't found.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/59daadd1-f370-4f39-b657-f9f108bf2627)

Currently, I'm confident that **v0.23.5** is good and stable.  Morbern (the KTL main sponsor) use it now and everybody is happy.

Cheers,
Norm
