### ISSUE TITLE
Forms won't submit

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#240]
Just had a call from Travis, he's the client we were working on the auto refreshing of a search component the other day. His app won't submit any forms, they all just hang. Just get the spinner as the watchdog is set to false.
The data is submitted but the form(s) won't close. It doesn't matter if its an add or edit form, they all hang. I disabled KTL and the app works as normal.

**Comment by CSWinnall** [comment]
For now I would I would suggest putting 0.22.20 in the version until this has been resolved.

**Comment by CSWinnall** [comment]
I have just tested some versions and 0.23.0 is stable.

Craig

**Comment by cortexrd** [comment]
Craig, do you see the issue? 
If possible, I'd like to debug with you or someone who has the bug.
ND

**Comment by CSWinnall** [comment]
I ve shared a fix on teams

**Comment by CSWinnall** [comment]
But we can debug if you'd like

**Comment by cortexrd** [comment]
It should be ok now.
Try **v0.23.4** please.

Again, very sorry for the trouble.  I need more testing/testers!
Norm

**Comment by CSWinnall** [comment]
If you let us know we have a testing app that we can try and break the KTL in.

**Comment by chprojectsupport** [comment]
Thank you @cortexrd - 0.23.4 has resolved the issue. I've connected with my client and he is happy again. I've added the version to the loader as he has a live client demo tomorrow so doesn't want anything to break overnight on a new update. Thank you @CSWinnall for your help and suggesting a roll back, I don't know why I didn't think of it. I'll remember for next time.

**Comment by cortexrd** [comment]
I've just released **v0.23.5** that fixes the issue Julian had with Inline editing.

I need to put in place several protection mechanisms against such outages.

1) A quick and easy, or maybe semi-automated roll back to last known working version.
2) A beta-testing plan for the volunteers.  So we can all test our app a day or two before switching officially.
3) Automated overnight testing on a known and controlled environment.

KTL is getting pretty complex and there are thousands of use cases that I can't cover alone in a day, without quitting my day job!  So it's time to tackle this challenge.

Thanks for your patience,
Norm
