### ISSUE TITLE
_nf On Reports

### ISSUE THREAD

**Issue by kukuk52** [cortexrd/Knack-Toolkit-Library#242]
I'm not sure if this is an issue or a request: It seems like the _nf keyword doesn't apply to reports. In my case, this is the place where the _nf is most needed. Is there any way to make that work with reports?

**Comment by cortexrd** [comment]
Hi Dan,

You're right, the _nf only works with Grid and List views at the moment.
I'll put that in the todo list.

There are 5 types of reports.  Which one(s) are you using?

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/2387abbd-6ee5-48a6-a732-af36a5e938d1)

Norm

**Comment by kukuk52** [comment]
If we could limit the filters on the pivot tables and then use the linked filters with filtering turned off on the other reports  (and I think that's already doable) that would work 95% of the time.

**Comment by cortexrd** [comment]
Hi @kukuk52,

It’s been a while, but I haven’t forgotten about you!

The _nf (No Filtering) issue on reports, including pivot tables, was addressed last week and should be resolved now.

Could you please test the beta code and let me know if everything works as expected?

Thanks,
Norm

**Comment by cortexrd** [comment]
@kukuk52,

If all ok, please close this issue.

Thanks,
Norm

**Comment by kukuk52** [comment]
Awesome, it seems to be working great! One idea for a future enhancement is to limit the filtering to specific fields (instead of going through and removing many fields the user could select the fields that they'd like to have available for filtering). In my case, there are a handful of fields that we'd like to allow users to filter and dozens that we need to hide. Having the ability to define the filtering fields would be much faster than removing all those that we don't want. For now, this is a fantastic enhancement. Thanks!
