### ISSUE TITLE
_cmr issue

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#243]
Hi Norm, please see the below Loom video which shows the issue I'm having on a page with a calendar. I only added _cmr to this form tonight and have reverted back to standard "redirect to parent" - not sure how its rendering a second calendar 🤷‍♂️
https://www.loom.com/share/9d7847bdd9b9467ebcfc0c7bfc2ba849?sid=ae01b47a-6cf3-42ab-a090-0eeb98b56591

**Comment by cortexrd** [comment]
Wow!!  You really are a magician, Carl.

If I'd try to do that, I'd never be able to do it without a lot of work.
BTW, can you do the same with money?  If not, then since you're good with calendars and time, I could live with 48h per day also!!!

On a more serious note, I'll see if I can reproduce this magic in my app and get back to you.

Norm

**Comment by cortexrd** [comment]
Carl,

I got it!  My app did the same, so I could fix the bug.

It's a very strange behavior from Knack:  for some reasons, Calendars don't need to be refreshed by the KTL.  They do it by default in Knack somehow.  I haven't investigated in depth why, but I simply removed this view type from the refresh list, and it did the job in my app.

Give it a try with the dev version and let me know how it goes,
Norm

**Comment by chprojectsupport** [comment]
Hi Norm,

Just tried it in Dev mode and it works as expected now, thank you for
investigating and providing a fix.

Please let me know when you have released an update so I can set up _cmr on
the form again.

Many thanks

Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com

**Comment by cortexrd** [comment]
You can go ahead Carl, it's been released now in **v0.25.7**.
Norm

**Comment by chprojectsupport** [comment]
Thanks Norm 🙏Carl HolmesOn 18 Feb 2024, at 16:37, Cortex R&D Inc. ***@***.***> wrote:﻿
You can go ahead Carl, it's been released now in v0.25.7.
Norm
