### ISSUE TITLE
_lub & _lud Issue

### ISSUE THREAD

**Issue by kukuk52** [cortexrd/Knack-Toolkit-Library#244]
I'm currently having an issue with _lud and _lub.  In addition to not capturing the data of when/who last updated a record in a grid, I see that both fields are available for inline edits when they shouldn't be if this keyword is working correctly. 

These seemed to work before and I'm wondering if there's anything that would cause these fields to stop working as expected. The grid and both fields are set to allow inline editing. Changing the KTL version didn't seem to make a difference either.

**Comment by kukuk52** [comment]
It seems like the issue is related to the _ttip that was added to the field after the _lub. For now, I've just removed the _ttip and everything is now working as expected.

**Comment by cortexrd** [comment]
Intersting, thanks for reporting.  I'll investigate...
Norm

**Comment by cortexrd** [comment]
Fixed!  Try dev mode.
Will be part of next release.
Norm
