### ISSUE TITLE
_afsg question

### ISSUE THREAD

**Issue by imelcher** [cortexrd/Knack-Toolkit-Library#247]
Hi,

Not sure if I am doing this correctly. I am trying to generate a QR code with afsg or afs/g in a members profile so that it can be used to populate a form in an attendance page. However the QR code does not generate once the information is put into the parameters. Also not quite sure if there should be a separate field that it should show up in...
On the simple _bcg I can get a QR code to show on the page but not with the other keywords. Not sure if I framed the question clear enough.

Thanks ahead of time.

**Comment by cortexrd** [comment]
Hi @imelcher,

To be honest, we don't have much information to work with... 😞 

Can you share your keyword string like this one:  
`_afsg=[landingPageUrl, formView, qrCodeSize], [qr, field1, field2,...], [auto, submit, close, closeDelay], [disable, field1, field2,...]`

And a screen grab of your page in the Builder would help also.

Tell us exactly what you intend to do:

1. Which field(s) need to be auto-populated
2. Any automation: none, Submit, Close or all?

What do you see vs expect to see.

Norm


Below is an example of a typical screen grab from the Builder that contains helpful information:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/fd890038-d845-41ab-bacf-b8e3da574fc8)

(I did it with the ShareX utility)

**Comment by imelcher** [comment]
Hi Norm, 

Sorry I been away and haven’t been able to look into this issue. 
The setup we have looks like this: _afsg=[https://wcmusa.knack.com/wcmusa-manager-app#attendance-page/?view_2487, view_2487, 200], [qr, Activity Date, Your Name, Local Church, Visit], [auto, submit, close, closeDelay]

This would hopefully create a QR are code that when scanned would direct to an attendance from to fill in the form and submit it with the date, the person’s name, there congregation(local church) and check off as visitor. 

Totally new to this, so I am pretty sure I am probably missing a few steps somewhere. 

Igor. 

At the moment I don’t see a QR code being generated anywhere.

**Comment by cortexrd** [comment]
Hi Igor,

I see a few things that could cause your problem.

1. Remove the **?view_2487** from your URL.
2. You can't have **closeDelay** as a parameter.  It should be a numeric value (in seconds) that the form will wait before closing.  I've chosen 5 seconds in your example below, so you can see that's happening.  You can change it to another value, or leave it out for instant closing.

`_afsg=[https://wcmusa.knack.com/wcmusa-manager-app#attendance-page/, view_2487, 200], [qr, Activity Date, Your Name, Local Church, Visit], [auto, submit, close, 5]`

Let me know if you see the QR code.

If not, maybe you could give me access to your page so I can see what's wrong.  Use this email:  nd@ctrnd.com and send me the password there.

Norm

**Comment by cortexrd** [comment]
Wait, I think I know what's happening.
The code expects some input field to be modified (typed-in characters).
I will modify it so that it displays the QR code at all times.

Will get back when it's done.

Norm

**Comment by cortexrd** [comment]
Also, there is important missing information in the documentation.
I will update that now.

**Comment by cortexrd** [comment]
I've updated the documentation:  https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Keywords#_afsg---auto-fill-and-submit--generate-qr

The code will be released a bit later today.
Norm

**Comment by imelcher** [comment]
Thank you Norm

**Comment by cortexrd** [comment]
Let me know if we can close this issue, or if there's something else to address.
Norm
