### ISSUE TITLE
Bulk Edit stalls

### ISSUE THREAD

**Issue by kbuena** [cortexrd/Knack-Toolkit-Library#257]
Hi!  New to the Toolkit Library but so appreciative that you've built it as it was sorely needed.  Wanted to report that often when I run a bulk edit operation I get the message that it is running the update, with the spinning circle indicating it's working, but it stalls and just sits there like that and never completes the operation.  This may happen with even a very small number of records.

**Comment by cortexrd** [comment]
Hi @kbuena,

Thanks for joining the KTL user's club!

About your issue, I suspect that it could be related to a Knack server error.
The way to find out is to check the console logs when this happens.  There are tons of tutorials that explain how to do this.  Personally, I prefer pressing the F12 key.  Works in Chrome and Edge, not sure about other browsers.
Then click on the console tab at top.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/b886c255-2d83-4826-bb72-7375b95c71c5)


If you see some errors, you can do one of two things:

1. copy the errors by clicking anywhere on one of them (to set the keyboard focus), then do Ctrl+A to select all, followed by Ctrl+C to copy the text.  Then paste here for analysis.
2. do a screen grab of that portion of the screen (or whole screen).  I use and recommend the free ShareX app.

Norm

**Comment by kbuena** [comment]
Hi, thanks!  I ran a bulk edit and got the stalling and here is the error:
k_f301f5cf706302db9eb0432e1788376d4a75c490.js:975 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at i.<anonymous> (k_f301f5cf706302db9eb0432e1788376d4a75c490.js:975:3298212)
    at d (k_f301f5cf706302db9eb0432e1788376d4a75c490.js:1:170234)
    at i.trigger (k_f301f5cf706302db9eb0432e1788376d4a75c490.js:1:169614)
    at i.handleLogout (k_f301f5cf706302db9eb0432e1788376d4a75c490.js:1:144443)
    at Object.logout (KTL-0.24.0.min.js:3:111221)
    at Object.ktlProcessServerErrors (KTL-0.24.0.min.js:3:129807)
    at Object.error (KTL-0.24.0.min.js:1:6589)
    at l (k_f301f5cf706302db9eb0432e1788376d4a75c490.js:14:7911)
    at Object.fireWith [as rejectWith] (k_f301f5cf706302db9eb0432e1788376d4a75c490.js:14:8700)
    at O (k_f301f5cf706302db9eb0432e1788376d4a75c490.js:21:41065)

**Comment by cortexrd** [comment]
It seems like you're getting a server 401 or similar error (login expired) and the KTL is forcing a logout in an attempt to recover from the situation.

Can you try to log out and back in to see if it helps?

Also, if the error persists, you can change **min** to **full** in the Loader.  This will give me readable code at the expense of a few milliseconds of extra loading time.  BTW, personally, I always leave this to full in all apps.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/c039ca9f-4909-49b4-9c91-0489b507b517)

Then re-copy the errors please.  They should be easier to understand.
You can also give me access to a dummy page that has the bug, so I can debug in a live app.  Send login info to nd@ctrnd.com

Norm

**Comment by kbuena** [comment]
Thank you, Norm.  I seem to have success when I log out and back in.  I will continue to play with this and see if I can further isolate when it happens.
