### ISSUE TITLE
Page Rules with _cmr

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#258]
Hi Norm,

As you know, I'm a fan of Close Modal Refresh (_cmr) keyword 😀
There is a very minor issue with using _cmr and a Page Rules as shown below:

https://www.loom.com/share/08f38b87222548c999bb98b6319d3e1a?sid=f30a97c8-d923-43b2-b8ac-cc10a26d711b

**Comment by cortexrd** [comment]
Carl,

That's a good one.  I'll see what I can do.  Should be easy to fix.
Will keep you updated.

Norm

**Comment by chprojectsupport** [comment]
I appreciate that 👍

Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com

**Comment by cortexrd** [comment]
Carl,

I've fixed the issue.

The only downside to the solution is that I have to force a page render (which is a bit faster than a full reload like F5), so the Page Rules can be re-applied as expected.

I tried the "quiet refresh" - that's when I just fetch the most recent data for the view, but nothing works.

You can try the **beta** version.

Norm

**Comment by chprojectsupport** [comment]
Excellent, thank you Norm, I really appreciate it 😉I’ll give it a try tomorrow 👍Carl HolmesOn 3 Mar 2024, at 19:02, Cortex R&D Inc. ***@***.***> wrote:﻿
Closed #258 as completed.

**Comment by chprojectsupport** [comment]
Hi Norm, I've tested this in Beta on several pages and although it works, I would like to ask that you do not implement the change please. The main benefit of _cmr is that it doesn't refresh the page and take you back to the top. After testing this now appears to function very similar to "redirect to parent" on form submit.

As this is an edge case I'd prefer to live with the fact that _cmr won't update a page rule. On the specific page I have the rule I'll just set the form to "redirect to parent". The benefit of _cmr would be lost if we roll this change out, unless I'm missing something?

**Comment by CSWinnall** [comment]
Hi @chprojectsupport 

We completely agree we've suggested to Norm that if  you pass in a view that CMR works as normal if you pass in CMR with no views then check if page rules exist.

What do you think.

Craig & Amanda

**Comment by chprojectsupport** [comment]
Hi Craig,Sounds like it could be a solution. Whatever works and is easiest. Carl HolmesOn 4 Mar 2024, at 17:47, CSWinnall ***@***.***> wrote:﻿
Hi @chprojectsupport
We completely agree we've suggested to Norm that if  you pass in a view that CMR works as normal if you pass I'm CMR with no views then check if page rules exist.
What do you think.
Craig & Amanda

**Comment by cortexrd** [comment]
Hi guys,

I think I've found the solution that does exactly what Craig suggested:

If you specify some views in the _cmr keyword, it will blindly refresh them, regardless of rules.  It will not remove any existing messages from the rules.

But if you leave the views blank, it will refresh all views, and re-apply the rules.

Try Beta or Dev version and let me know if it does the job.

Norm

**Comment by CSWinnall** [comment]
Thank you, Norm,

This is working well thank you for making those changes.

Craig
