### ISSUE TITLE
_ttip Does Not Display When Records are Grouped

### ISSUE THREAD

**Issue by kukuk52** [cortexrd/Knack-Toolkit-Library#259]
Tooltips will disappear on a grid when using Knack's "Group records based on this field's value" option.

**Comment by CSWinnall** [comment]
Hi @kukuk52 

You are right that the tooltips won't appear on the groupings this is due to the fact that Knack doesn't include a fielId to target in the groupings.  We could add ktlTarget to the view keyword to fix this in the near future but I don't think this could be applied to the field keyword.

If you are saying that all tooltips disappeared when a table is grouped then that is an issue. 

Can you let me know which problem it is please.

Craig

**Comment by kukuk52** [comment]
Hey Craig,

All the tooltips disappear when the table is grouped--not just those within the grouped field. 

Dan

**Comment by CSWinnall** [comment]
Are you using any other keywords on the grid?

**Comment by CSWinnall** [comment]
You are right I'll look into this and get back to you.

Craig

**Comment by CSWinnall** [comment]
This also breaks some of my own keywords can't believe I haven't spotted this before.

**Comment by kukuk52** [comment]
Thanks for looking into it. For what it's worth, yes, I'm using a lot of other keywords. Primarily, a series of _hc to allow users to view the specific columns they want available in their view. Like this: _hc=[Job Title],[ktlCond,hasnt, Job Title, field_1592,  view_1819]. There are some other ones in there too.

**Comment by CSWinnall** [comment]
Ok thank you I don't think it's that but it's worth bearing in mind while I look for the issue.

Craig

**Comment by CSWinnall** [comment]
Hi @kukuk52 

@cortexrd has already fixed this in ver 0.24.0 which he should be releasing soon.

Craig

**Comment by kukuk52** [comment]
Great news! Thanks @CSWinnall and @cortexrd.

**Comment by cortexrd** [comment]
Guys,

Do we still have this issue in Beta mode?
I've tested and I still see the ttips when grouped.

But indeed, we lose the one for that group, which is normal since there's nowhere to put the icon.  Unless we want to add it to each group?

Norm

**Comment by amandajane-mo** [comment]
Hi Norm,

Issue is fixed in Beta.

I don't think we want tooltips on the grouped by row, it would be repeated down the table, I can't see the need for it - others may disagree. No field ID on the grouped row so would be tricky to target.

Amanda

**Comment by kukuk52** [comment]
It is working in 24.0 and in beta mode. I'm currently still running 23.9 given the form issue. 

I agree, there's no real need to add the ttip to each group. 

Dan
