### ISSUE TITLE
Error with cmr

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#261]
Hi Norm

I am on version 0.24.1 I am getting this error 
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/ddf96ece-0858-478a-b7b2-eac2d0eff43f)

I have _cmr no params on a form view I do not have any page rules on the modal or the background page.

Craig

**Comment by cortexrd** [comment]
Should be fixed now.
Try Beta or Dev version.

Norm

**Comment by CSWinnall** [comment]
Thanks Norm
