### ISSUE TITLE
Issue With _hf in Version 24.0

### ISSUE THREAD

**Issue by kukuk52** [cortexrd/Knack-Toolkit-Library#262]
I'm using a set of _hf conditionals in a form that allows admins to determine the information they'd like displayed in that form (_hf=[field_1278],[ktlCond,hasnt, Departments, field_1356,  view_1878]). 

When updating to the new 24.0 version of the KTL the entire form is hidden. When I revert to 23.9 everything displays as expected.

**Comment by cortexrd** [comment]
Dan,

Can you try the Beta code please?
I may have found the cause, but not sure.

Norm

**Comment by kukuk52** [comment]
No luck. The form displays for a second and then disappears.  Thanks for looking into this. 

Dan

https://www.loom.com/share/7047df83c11d440db5dcbac661595ffe?sid=3120336c-0c30-4f80-b2d7-038b729b83a3

**Comment by cortexrd** [comment]
Dan,

I managed to log-in your app and reproduce the bug.
This led to a solution that you can try in Beta.

BTW, it had nothing to do with _hf keyword, but rather with the combination of **_ro** and the signature field.  If you remove one or the other, the bug doesn't happen.

Let me know if it works,
Norm

**Comment by kukuk52** [comment]
Hey Norm, 

It works! Apologies for the misdiagnosis.  Thanks for getting to the bottom of it and providing a solution.

**Comment by cortexrd** [comment]
Hey... no problem!

I'm so happy to see that it will be solved in next release.
And in the process, it provided an opportunity to explore a much better solution to similar issues for the future.

ND
