### ISSUE TITLE
Tooltip Issue

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#268]
Hi Norm,

As you will see from the below Loom, I'm having an issue with the tooltip popup being truncated on a search view when the column is close to the edge of the table.

https://www.loom.com/share/240f139a87464b9bae92bbf382f74b1a?sid=211efd22-8e71-4186-8bda-57b63daeaa14

**Comment by CSWinnall** [comment]
Hi Carl 

I'm looking into it

Craig

**Comment by CSWinnall** [comment]
I have just fixed the code and requested Norm review it so it should be with you when he can look at it.  It was also an issue on table views too.

Craig

**Comment by chprojectsupport** [comment]
Great, thank you Craig 🙏

**Comment by cortexrd** [comment]
Hi guys,

I've just released a Beta version with the latest fixes from Craig.

Norm
