### ISSUE TITLE
Inline Edit Duplication on field that has Insert a Connected Record - Only When Pressing Enter to submit the inline edit

### ISSUE THREAD

**Issue by rgolchin** [cortexrd/Knack-Toolkit-Library#274]
Hello,

I have come across a bit of a strange problem and hoping that you can assist me. 

The issue that I have come across is that on a field that I have a record rule to Insert a Connected Record in a connected table, I am seeing a duplicate entry - ONLY when I press the Enter button on the keyboard to submit the entry in the grid. When I remove your code all together from the Code section of the app the issue goes away. 

Wondering if you have come across this before or can help me with this.

**Comment by cortexrd** [comment]
@rgolchin,

Thanks for reporting this.  It's strange indeed and needs to be addressed.

I am not sure I understand where you see the duplication exactly.  
It you re-open the inline edit, do you see the duplicate entry, or only in grid itself?
I understand it's being triggered by the inline edit's submit.  But is it only with Enter key or also with a mouse click?

Is it possible for you to create a debug page that I can access and do some testing and properly assess the issue?
If so, use this email:  nd@ctrnd.com and send me the PW at that address.

Norm

**Comment by rgolchin** [comment]
Hello,

I have a connected table in the background that is getting two records inserted in it. I also have a SUM field in the parent table that I am using for the calculation and it is throwing the calculations off. I have attached a video of my screen here and also the duplicate records in the connected table. Lets start from here and if you still need access to investigate I will create it.

In the video you will see us entering 100 for the Qty Packed out of the 200 and the Field Qty To Pack (in Yellow) should have reduced to zero, but because of the duplicate entry in the connected table it is going down to zero.
When we take the javascript code off (for KTL) the issue goes away.

Video:
https://drive.google.com/file/d/1FzPIwBL40q-B72vAxJpAnOQZ_QvDkrxM/view?usp=sharing

Screenshot of the connected record being duplicated:
<img width="1338" alt="Screenshot 2024-03-28 at 9 27 19 AM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/43184950/7e1ec00c-66d6-46be-b48f-b17511bf6d2c">

**Comment by rgolchin** [comment]
I just wanted to add that with the KTL code in there pressing the Submit button (rather than the Enter Key on inline Edit as per the video) works and does not duplicate the record in the connected table.

**Comment by rgolchin** [comment]
Hello just checking in to see if I can get a response rather soon. We are going live with an app next week and need to make sure it is all good before go live. Thank you.

**Comment by cortexrd** [comment]
@rgolchin,

Everything is clear now.
I will try to reproduce in my app, and keep you updated ASAP.

Norm

**Comment by cortexrd** [comment]
@rgolchin,

I found the issue.  Knack used to ignore the Enter key in inline editing, so I added my own code that clicked on the Submit button programmatically upon Enter keypress.  But they've fixed that recently, and my code was causing a double-click on the Submit button.  That's why.

Can you test the Beta version please?
If all works well, I will do a release in a day or two.

Norm

**Comment by rgolchin** [comment]
Thank you very much. I am still seeing the same behavior with the duplication. When you say beta, do you mean this code?

KnackInitAsync = function ($, callback) { // Load the Knack Toolkit Library (KTL)
    (window.LazyLoad = LazyLoad) && LazyLoad.js(['https://ctrnd.s3.amazonaws.com/Lib/KTL/KTL_Start.js'], () => {
        loadKtl($, callback, (typeof KnackApp === 'function' ? KnackApp : null), '' /*KTL version, leave blank to get latest*/, 'min'/*min or full*/);
    })
};

**Comment by cortexrd** [comment]
No, I mean switching to Beta using this method:  https://github.com/cortexrd/Knack-Toolkit-Library/discussions/186#discussioncomment-8088216

**Comment by cortexrd** [comment]
**Enter a single letter** to select the desired code version **'b' for Beta**

**Comment by cortexrd** [comment]
@rgolchin,

I will close this issue now.  If you see the bug again, feel free to re-open it.

Norm
