### ISSUE TITLE
Field Tooltip floating to the top of page and out of view

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#275]
I am using the _ttip keyword in a field and on a grid view and the tooltip is popping up at the top of the page and partly out of view. I don't see the CSS for this in the inspector so I assume it may be hiding and displaying via javascript. Is it my setup or is this an issue in the toolkit and how can I diagnose the issue if it is only our setup?

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/b3fc748c-a2c4-4dd1-bfef-6b5853ea90a0)

**Comment by CSWinnall** [comment]
Interesting.  I'll try and replicate it and get back to you.

Craig

**Comment by CSWinnall** [comment]
Is this the first time you have used ttip and can you replicate this issue on another grid?

Craig

**Comment by CSWinnall** [comment]
It was really tricky getting the ttip to work on tables/grids due to overflow issues.  Can I ask if you turn your code off for the groupings does it still appear at the top?

I'm wondering if the equation is running before your groupby code which means the offset position is wrong.
Craig

**Comment by djbbiz** [comment]
Here it is on the table/grid below that doesn't have Groupings. In order to be able to see it on screen I had to change the browser Zoom to 67%. At 100% it doesn't appear as it is off the screen.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/b304d26a-6115-487d-9391-a45411b439c5)

**Comment by CSWinnall** [comment]
Hi Sorry I've had a couple of weeks off.
Is there any way we could meet to discuss this issue. I can't replicate it anywhere on my app.


Craig

**Comment by cortexrd** [comment]
Hi guys,

I've fixed the bug, and also added protection to prevent overflowing out of screen.

Fixed in current version: **v0.24.12**.

Enjoy,
Norm

**Comment by CSWinnall** [comment]
Hi Norm 

I've just done a quick test and the tooltips now scrolls with the screen I.e. it doesn't stick to the icon when on a mobile.


This might be due to it being position fixed?

I'll test it more tomorrow.

Craig

**Comment by cortexrd** [comment]
Yes, the position is fixed.  That was the best solution I could find to bypass the zoom problem.  At least you see the tooltip right next to where your mouse (or tap) is.  That was the important part.  After that, if you scroll up or down... maybe we should simply remove the tooltip if more than a threshold number of pixels like 20px - or a delay 500ms?

If you want to improve on this, please feel free to experiment.

ND

**Comment by CSWinnall** [comment]
Ah it was zoom causing the issue. I missed that.

Craig

**Comment by djbbiz** [comment]
Working on my desktop now, haven't tried mobile - Thanks for the fix appreciate you staying on top of this as I know not all issues are critical but small enhancements like this make a big difference in UI and necessary support of an app.
