### ISSUE TITLE
Reload form link not showing

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#276]
Hi @cortexrd 

The Show a link to reload the form isn't showing on our forms after a submit.  I have bypassed the KTL (v. 0.24.8) and the link shows again.

With KTL on:
<img width="420" alt="Screen Shot 2024-04-02 at 15 47 29" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/49612a48-f02f-4651-9ccc-742b10fcb941">

With ktl off:
<img width="431" alt="Screen Shot 2024-04-02 at 15 49 09" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/e76faf29-2ed1-4e7c-b13d-e8d44004d92e">

Not sure how long this has been happening as we rarely use the option to show a link to reload form. 
Craig

**Comment by CSWinnall** [comment]
Unfortunately I am not in a position to figure out the issue at the moment.

**Comment by CSWinnall** [comment]
Hi Norm

<img width="665" alt="Screen Shot 2024-04-03 at 15 39 16" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/7f26c160-f645-4f59-a89d-79889b0b6e26">

When I commented the above line of code the reload link showed again.

Craig

**Comment by cortexrd** [comment]
I found the solution.
Can you test Beta please?

Norm

**Comment by CSWinnall** [comment]
Thanks Norm that's fixed
