### ISSUE TITLE
_style doesn't seem to be working for me in recent versions

### ISSUE THREAD

**Issue by LeighBerrell** [cortexrd/Knack-Toolkit-Library#278]
I am using KTL to reposition and resize the SSO login button on the login page, so its not stuck off to the right of everything else.  (who in Knack thought that was a good idea?)

The script below is working fine with v.0.22.19 (which was current when I set this up) but if I use any of the more current versions it doesn't work at all - the button remains in its default location and remains the default size.   So I'm unable to use any more recent version of KTL than 0.22.19 until I can work out why this is.   

Any ideas on what may have changed? 

_style=[min-width:450px;color:#b70000;border-color:#b70000;background-color:#ffffff;position: absolute; left: 20;z-index: 100],[ktlTarget, $('.kn-sso-container')]

This first image is what I'm trying to achieve, and how it looks now with v0.22.19 loaded

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/c0c824b7-a329-4389-a67e-d3e225b9be0c)

This second image what it looks like with any latest version of KTL loaded (either by specifying something more recent or just leaving it null).  You can see the button remains in default place and size.   

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/5e4360ab-598e-4c55-98e9-face8bbe8e14)

**Comment by LeighBerrell** [comment]
If it helps, I stepped through some versions to see where it "breaks".  It works with 0.23.2 but doesn't work with anything higher than that.

**Comment by cortexrd** [comment]
I fixed the bug.
Please test the Beta version.

Norm

**Comment by LeighBerrell** [comment]
Thanks Norm, this is working properly in beta so I think its fixed!

**Comment by LeighBerrell** [comment]
Norm, I note that this is no longer working in the BETA version - should it be?

**Comment by cortexrd** [comment]
It's possible that I might have overwritten the fix by mistake.

I've re-uploaded Beta and tested: all is good here.

Let me know how it goes on your side,
Norm

**Comment by LeighBerrell** [comment]
Thanks, that is working again with beta.

How long before you are likely to move that fix into production?

 

Rgds

 

Leigh Berrell

0412 100 045

**Comment by cortexrd** [comment]
Hi @LeighBerrell,

It is available in the coming version 0.24.9 if you want to switch to it now.
I'm just not quite ready to do a full-scale deployment today, not being at home.
But it's in use by my client (Morbern) for 3 days now without problem, so it looks good for an official release Wednesday.

Norm
