### ISSUE TITLE
Tooltip Issue

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#283]
Hi Guys,

It's taken me a while to figure out why one of my tables was working so slowly. Specifically, the hover would be almost a second behind the position of the mouse cursor. It relates to a _ttip, which I'd added to a field that was an edit link, so I can't add the tooltip to a data field as there isn't one. The tooltip works, but for some reason, it makes the grid very unresponsive. In fact, using Microsoft Edge, which is not my daily driver, makes the table almost unusable.
As you can see from the below video, I have removed the _ttip from the setting of the grid, and the hover over and tab navigation performance is re-instated.
It's certainly not a show stopper, but I thought I should raise it. 😀

https://www.loom.com/share/7494a98e26f14b50bb9c6146986dcd95?sid=32bde29a-9f03-471d-9f3f-f9ad9dddae91

**Comment by CSWinnall** [comment]
Hi Carl

Well spotted.  We will look into this for you.  It only affects view tooltips that are applied to action links.  Very Odd.  It also happens on older versions of KTL.

C & A

**Comment by chprojectsupport** [comment]
Thanks @CSWinnall - it is an odd one. 🤷‍♂️

**Comment by CSWinnall** [comment]
Hi Carl

#284 This pull request should fix the issue.  I have made the target of the event listener more specific to the icon so it isn't listening to all the mouse movements which was causing the lag.

Craig

**Comment by cortexrd** [comment]
Hi guys,

I am preparing for a big release today.  It will include the PR from Craig to fix this issue, and also the long-awaited _req (Required) feature.

I will let you know when it's ready for Beta testing.

Norm

**Comment by CSWinnall** [comment]
> Hi guys,
> 
> I am preparing for a big release today. It will include the PR from Craig to fix this issue, and also the long-awaited _req (Required) feature.
> 
> I will let you know when it's ready for Beta testing.
> 
> Norm

That's Exciting 
Can't wait to test.

**Comment by chprojectsupport** [comment]
Cheers Craig 👍Carl HolmesOn 28 Apr 2024, at 15:32, CSWinnall ***@***.***> wrote:﻿
Hi Carl
#284 This pull request should fix the issue.  I have made the target of the event listener more specific to the icon so it isn't listening to all the mouse movements which was causing the lag.
Craig

**Comment by cortexrd** [comment]
Ok, you can try the Beta code now.

It has the PR #284 and the new _req code.

Example:

`_req=[Sale Price, Reg Price], [ktlRoles, Sales Clerk]`

Will set the fields Sale Price and Reg Price as required, but only for those with role Sales Clerk.

I am working on ktlCond now, so it may not be fully functional yet.
Also, _req only works for all text types, connections and date/time fields.  I will add support for all fields when I have more time.

Norm

**Comment by CSWinnall** [comment]
We will try it out tomorrow.

**Comment by cortexrd** [comment]
ktlCond is also working, but only with Details views.

**Comment by cortexrd** [comment]
Docs here:  https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Keywords#_reqfield1-field2
