### ISSUE TITLE
_req Still Submits the form

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#285]
Hi Norm

I have tried adding _req to a form on a short text field.  The field goes Red if the input is empty but I can still submit the form if it's empty.

Here is the keyword I am using: 
_req=[field_3165]

Craig

**Comment by cortexrd** [comment]
Craig, I can't reproduce your bug.
Can you give me access to your page?

BTW, I've just pushed the latest code in dev and uploaded it as Beta if you want to refresh and give it another try.  Maybe your bug will be fixed.

**Comment by CSWinnall** [comment]
Hi Norm
I've tested in the latest dev code & Beta:  Here is the page

https://arcproject.knack.com/arc-beta#debug/client-funders2/

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/094cacdf-82d8-4d2e-9d2b-f23158cc0487)


Craig

**Comment by cortexrd** [comment]
I've reset my PW, but I get access denied error.

**Comment by cortexrd** [comment]
Forget about that.  I can see the page, but the pink color doesn't show up when empty.

**Comment by CSWinnall** [comment]
Sorry Norm

I had to change the page if you go back to my post I've edited it to the
new page sorry about that.

Craig

**Comment by CSWinnall** [comment]
Thanks for your help Norm

Form formPreValidation needs to be turned on in the config for this to work.  Working as expected
