### ISSUE TITLE
Tooltips Not Working Outside KTL Beta Code

### ISSUE THREAD

**Issue by kukuk52** [cortexrd/Knack-Toolkit-Library#292]
It seems like my tooltips are not working unless I have the KTL-beta code enabled.

**Comment by CSWinnall** [comment]
Hi Dan 

Can you let me know what version you're using please?

Craig

**Comment by kukuk52** [comment]
Hey Craig, 

We're running 24.9 but I tried 24.2 and 24.0 and I'm getting the same issue. When I hover over the tooltips nothing. In Beta everything is working as expected. 

Dan

**Comment by CSWinnall** [comment]
Hi Dan

It looks like the CSS file has been updated ahead of the JS so until @cortexrd updates to the next version of KTL can you paste this CSS into your CSS pane in the builder.

```
#knack-body .ktlTooltip{
  position: absolute;
  display: block;
}
```

This will fix it until Norm update the prod to the latest version.

I am sorry about this.

Craig

**Comment by cortexrd** [comment]
So sorry guys, I completely overlooked this.
I will try very hard to do a release today - it's long overdue!

Norm

**Comment by kukuk52** [comment]
Thanks for the quick fix @CSWinnall. Thanks for all the work you're putting into this @cortexrd. I'm looking forward to the next release.

**Comment by cortexrd** [comment]
Dan,

Can you confirm that all is ok with v0.25.0 please?
I will close this issue assuming that it's the case.

Norm
