### ISSUE TITLE
Context-Sensitive Right-Click Menu Issue with User Filters

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#293]
Hi Guys,

Please see the below issue:

https://www.loom.com/share/2b77da778db54280adad889ffd895eea?sid=1ad52586-61b9-4ff9-ac04-68bfe9d769e0

**Comment by cortexrd** [comment]
Hi Carl,

I tried to reproduce this here but can't do it.

@CSWinnall, any luck on your side?

I suspect it might have something to do with the Live App Design settings.
I tried a few changes like Legacy and Sticky Headers but no success.

Norm

**Comment by cortexrd** [comment]
Go it.  It's this:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/b7a63511-e451-4eac-a93f-5e105f75b18b)

The z-index should be 6 not 3.

I will update this in next release.

@chprojectsupport, can you test the Beta version please?

Norm

**Comment by chprojectsupport** [comment]
Very strange, I've definitely had it working before on other apps.

I've re-checked and I don't have any other code running on the grid
view, only the KTL sticky headers. If I remove _sth=, 700 it still renders
behind the table header, with no sticky header?

Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com

**Comment by cortexrd** [comment]
And the Beta code doesn't solve that?
ND

**Comment by cortexrd** [comment]
Can you inspect the header and check it's z-index value?

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/90a295ed-d22e-41b2-9dbb-0c63987d19cb)


![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/6606869b-b96e-452a-ae6b-0d70b44b4a2e)

**Comment by chprojectsupport** [comment]
There isn't a z-index in the element.style section. I've also searched for
"index" which produces no results in the DOM.

[image: image.png]
Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com

**Comment by CSWinnall** [comment]
Hi Norm

I just realised that we set the z-index of the menuDiv to 3 quite a long time ago.  Because of this issue.

Craig

**Comment by chprojectsupport** [comment]
This has been resolved after talking with Craig this morning. There was some CSS setting the z-index to 20 which I have reduce to 2 and now the menu appears correctly. 
My bad 😢
Thank you Craig for all your help 🙏
