### ISSUE TITLE
_mc keyword not working

### ISSUE THREAD

**Issue by Ampurcell** [cortexrd/Knack-Toolkit-Library#294]
Hi Norm, Hope you are well! 
Ok. So I have code all over my app. It has been amazing. I love _mc. I was one of your first and it has helped. 
I have added a new section to my app and I can't get it to work. I have no idea what I am doing wrong. The code works in the previous areas. 

**HERE View_1872 - The code works great! _trk works great too!** 
<img width="1062" alt="Screenshot 2024-05-18 at 9 39 42 AM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/141195753/c332d945-2cba-42ce-99d1-fc181bc832ec">

![Screenshot 2024-05-18 at 9 40 24 AM](https://github.com/cortexrd/Knack-Toolkit-Library/assets/141195753/64ea0b88-c59a-4fe0-82a5-42aeab544bb8)

I created a new record table, and I am creating new pages, grids, and views for it. But I can't get the same code to work! 

View_2084 I added _mc=status and _trk
![Screenshot 2024-05-18 at 9 25 39 AM](https://github.com/cortexrd/Knack-Toolkit-Library/assets/141195753/22ec1c95-e140-4747-9033-02d724cc3498)

<img width="1094" alt="Screenshot 2024-05-18 at 9 25 25 AM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/141195753/afa8d661-a00e-4631-a870-acc1a5f215a3">

Any Idea? What am I doing wrong?  

I finally got the developer tools, lol, And I even updated it to the latest version. 

<img width="189" alt="Screenshot 2024-05-18 at 9 43 35 AM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/141195753/2e19c1f5-9b45-48f6-a76a-2417ec6d524c">

**Comment by cortexrd** [comment]
Hi Alisha,

This is unexpected indeed.  It should work.  Did you check the console logs?

Can you give me access to this page?  If so, send me the password at this email:  nd@ctrnd.com
I already have the link you gave me in an email.

Norm

**Comment by Ampurcell** [comment]
I don't even know how to check the logs. I sent you a PW. I am sure I broke something. I think I made things worse when I was trying to trouble shoot myself.

**Comment by cortexrd** [comment]
Alisha,

I am now in your app, on the page with the issue you're having.  There is a bug indeed.

But I can't see any data.  When I add an entry, it disappears right away...
Can you populate some rows for me so I can see something?

Norm

**Comment by Ampurcell** [comment]
Which packlist are you viewing. The packlist line items are linked to the packlist name. 

Let me make a dummy list. 
https://productions.knack.com/productions-by-gilad#event-calendars/event-name--client-details/664b50111db7580029e3cafd/add-packlist/664b50111db7580029e3cafd/create-packlist/664bc24f2c2340002797cfc3/view-packlist-details2/664bc24f2c2340002797cfc3/?view_2084_filters=%5B%5D

**Comment by cortexrd** [comment]
It's ok, I managed to see something last night.

But then, I stumbled on another bug due to grouping.
But I should be able to fix this today, depending on my workload with Morbern.

I'll keep you posted,
Norm

**Comment by cortexrd** [comment]
@Ampurcell,

I've fixed all bugs, but only in the **Dev** version for now.  I will do an official release shortly, hopefully today.
Can you test the Dev version please?

Click here to see how to do it:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/2a7ea50d-64d1-48ed-8dea-2415c70cefc8)

Norm

**Comment by Ampurcell** [comment]
Sweet! Dev works. 
Hopefully, it wasn't me who broke it, lol.

**Comment by cortexrd** [comment]
Glad to read that it works now.

Don't worry, you have nothing to do with the bug.  It's all KTL's fault!!!

I'll close this now.
Feel free to re-open if you see anything else related.

Cheers,
Norm
