### ISSUE TITLE
Populating Hidden Field on Form with Javascript

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#299]
I have a form that requires a record to be populated with the Account Id it is associated with. I use the code below to populate the Connected Account field_218. I was hiding the field_218 on the form using _hf= but the field stopped populating unless it is visible on the form. When I created this awhile back the fields was populating when hidden but something seems to have changed so that the field can't be hidden now.   

`$(document).on('knack-view-render.view_187', function(event, view, data) {
	// The connected record id value
	//alert(contactId)
	var connectionId = contactId;
 console.log('view_187 Connection ID set to: ' + connectionId);
	// Update the view and field ids for your application
	$('#view_187-field_218').val(connectionId);
	$('#view_187-field_218').trigger("liszt:updated");
});`

**Comment by cortexrd** [comment]
@djbbiz,

So, if you **don't hide** the field, all is working as expected?  (did you actually try that?)

BTW, this is your code, formatted for improved readability:

```
$(document).on('knack-view-render.view_187', function (event, view, data) {
    // The connected record id value 
    //alert(contactId) 
    var connectionId = contactId;
    console.log('view_187 Connection ID set to: ' + connectionId);
    // Update the view and field ids for your application 
    $('#view_187-field_218').val(connectionId);
    $('#view_187-field_218').trigger("liszt:updated");
});
```

I tried to log in the app you gave me access a while ago (tedtasks), but I think it's another one.  I don't see anything related to view_187 or field_218.

If you could give access to the new app, it would help a lot.

Norm

**Comment by djbbiz** [comment]
That is correct when I take off the hidden keyword the account field is populating properly. And you are correct it isn't in TEDtasks it is in another app. I will contact you directly with more info.

**Comment by amandajane-mo** [comment]
Hi Dean,

If you hide a form input using _hf, you won't be able to submit any data via that field. You'll need to use ktl class ktlHidden, something like this:

`_cls=[ktlHidden], [ktlTarget, $('#kn-input-field_xyz')]`

This is because _hf sets the field to display: none, and for security reasons you can't submit data in fields hidden in this manor. Using ktlHidden moves the field off the page, so you can't see it and your data will be submitted.

Amanda

**Comment by djbbiz** [comment]
I believe you are correct about the use of the ktl Class but _hf was different and working before for this purpose.As it still appears in the DOM as you can see so it isn't truly gone from the DOM it should be accessible through javascript. 

<img width="1530" alt="image" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/afd26fe2-0277-4195-bf91-144998cb156a">

**Comment by djbbiz** [comment]
The above was a test, here is the original issue and you can see that I have the Account field_218 hidden in the form yet it appears in the DOM and I am in the Test User and my javascript is indeed acting with the field in the DOM and setting the Account field to Test User. But when I save it isn't recording the Test User Account so I suspect maybe there is another issue that is deleting that selection before my saving the form. But not an issue when the field is visible.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/8e14af52-8725-40f2-bece-c5db4b406a1f)

**Comment by cortexrd** [comment]
@djbbiz,

Try the latest release v0.25.6 please.

Norm

**Comment by djbbiz** [comment]
Hey Norm, I just tested and everything seems to be back to normal and working. Thanks for a fast fix!

**Comment by cortexrd** [comment]
Great, very happy to read that - thanks for reporting!
Norm
