### ISSUE TITLE
Spinner Watchdog

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#300]
I have the setting for  spinnerWatchDog: false, and it works fine when I am directly accessing the app from Knack but when the app is embedded into another app the spinner keeps going, I am guessing due to issues in the other app.

Is there anything that would work different for spinnerWatchDog: false, if the app is embedded as opposed to directly accessed?

**Comment by cortexrd** [comment]
Hi Dean,

That's a setup I've never used yet, so it's hard to tell what's happening without seeing.

BTW, the spinnerWatchDog is a KTL interval (periodic 1 second timer) that keeps an eye on Knack's spinner, and if it's visible for more than 30 seconds, it reloads the page - or do whatever you decide.

Now, setting this to false simply disables the watchdog.  This means that the KTL will ignore the spinner. It will keep going forever without any expiration and any action taken.  It will not prevent the spinner per se.

Now my questions is:  that spinner... is it really Knack's, or a similar one but using different classes, not properly detected by the KTL?  Only a close examination of the HTML will reveal that.

Let me know if I can access your app in a page that has the issue.

Norm

**Comment by djbbiz** [comment]
Sorry Norm, I found the issue, the spinner was getting turned back on in some javascript and not shutting off due to an API access issue I need to figure out so setting is working as intended.

**Comment by cortexrd** [comment]
Good news!
Let me know if you find anything else.
Norm
