### ISSUE TITLE
_style gets added twice

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#304]
Hi Norm

When using _style we have noticed that the style is added twice.  

_style=[margin-bottom: 75px]
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/f4db521a-77d4-465a-b3ec-dbf8a6a20af2)

This is not a new thing, it has been doing this for a long time.

Craig

**Comment by cortexrd** [comment]
Yes, I noticed that also.
Actually, every time you refresh the view it will add a new instance of style, growing indefinitely.
I've created a function to fix that, but it's not fully implemented yet, being used internally in a function for now.

I need to expose it and use it more liberally, like in the _style keyword.

@CSWinnall, if you want to try it, you're welcome.

Norm

**Comment by cortexrd** [comment]
See **function mergeStyles(baseStyles, newStyles)**
This will be moved to core:

**ktl.core.mergeStyles(baseStyles, newStyles)**

If a style already exists, it will be updated with newStyles, and if not, it will be added.

**Comment by CSWinnall** [comment]
Thank you I'll take a look.

**Comment by CSWinnall** [comment]
Ok I've created a branch to work on it
