### ISSUE TITLE
Issue loading configurator from LS

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#307]
There is an issue with loading the configurator file from local storage. 

When we added the pendingClass to quick toggle we had to allow for the fact that the parameter pendingClass wasn't stored on the file that was saved. I am wondering if that is the problem.

**Comment by CSWinnall** [comment]
I'm going to close this as it's something to be aware of when you add new flags to the configurator rather than a specific issue.

**Comment by cortexrd** [comment]
Noted.  Good point.
Since we're not at version 1.0.0 anymore, we must always provide a default initialization for future parameters.
