### ISSUE TITLE
Inline edit turn off submit when enter is pressed for text areas

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#31]
Hi Norm

Is there a way to turn off pressing enter to submit an inline edit?

Our users when using textareas like to leave empty lines to break up different notes.  Which they can't do as hitting enter submits the form. 

Craig

**Comment by CSWinnall** [comment]
Hi @cortexrd 
So we have a temporary fix which is 

`$(document).on("keydown", '#cell-editor .kn-textarea', function(e) {
  console.log('In Event')
  if( e.keyCode == 13){
    this.value = this.value.substring(0, this.selectionStart)+"\n"+this.value.substring(this.selectionEnd,this.value.length);
  }
  return e.key != "Enter";
});`

But this will still cause our users some issues as the cursor jumps to the end of the text every time they hit enter.  We are looking at getting the position of the cursor and sending the cursor back to where it was.

I'd really appreciate some help with this as we have now put KTL on our live app and we really like using it.

Craig

**Comment by cortexrd** [comment]
Craig,

Actually, what I'd propose is to change the behavior so that you'd press **Ctrl+Enter** to do a Submit in scenarios where you do an inline edit on those special text fields.  Pressing Enter will just add a new line as expected.

I will test for Paragraph text and Rich Text field types.

Norm

**Comment by CSWinnall** [comment]
Hi @cortexrd 

This all works now thank you.

Craig
