### ISSUE TITLE
Auto Refresh Jumps when Filters are Engaged

### ISSUE THREAD

**Issue by Greenlight88** [cortexrd/Knack-Toolkit-Library#318]
Hey Norm and all - I clocked this a couple of days ago but misdiagnosed - there is an issue with auto refresh and how it interacts with filters on a grid view

If you have any filter engaged on a grid view and you navigate to a second page it will jump back to first page on refresh

If no filters engaged the behaviour does not manifest

This is true even if its a 'nothing' filter Like 'Show All' set to Consultant is Any or similar - which you might have present so you can set it as the default view

**Also** if the grid  was long with a scroll bar and you were scrolled down at the time of refresh, the scroll will jump to the top on refresh if filters are engaged. 

Again this does not happen in an unfiltered grid.

 Am using version 0.27.4, latest

**Comment by Greenlight88** [comment]
I forgot to mention am using version 0.27.4, latest

**Comment by cortexrd** [comment]
I've tested that and I don't see any of the behaviors you're describing.

Just to be sure I understand well:

1. I have Page A with a grid with 200+ records, an active user filter (with a saved button) and auto refresh every 5 seconds.
2. If I navigate down or at the bottom of the page, it would scroll up every 5 seconds?
3. I navigate away to Page B, it will jump back to Page A within 5 seconds?

Do you have Summaries and Grouping?

Can you confirm of clarify what I enumerated please?
And if possible give me access to that page or a similar one?

Norm

**Comment by cortexrd** [comment]
Michael,

Actually, I can still access your app.  I am logged-in currently.
Can you give me a link where you see the issue and a precise sequence to reproduce it?

ND

**Comment by Greenlight88** [comment]
here yes hang on

**Comment by Greenlight88** [comment]
Hoping you n see our Enquiries tab?

If so just so go to First Tab No spa or Duplicates and use any filter

**Comment by Greenlight88** [comment]
(soe of y keys not working sorry)

ill hek your perissions

**Comment by Greenlight88** [comment]
https://greenlightservices.knackhq.com/greenlight-online#enquiries4/no-spam--duplicates2

**Comment by Greenlight88** [comment]
so you should see the behaviour on there the _ar is set to 5 seconds if any filter engaged will scroll to top of grid on refresh or if on page 2 of the grid will go bak to page 1

**Comment by Greenlight88** [comment]
interesting just noted with the scroll - behaviour is different if the cursor is on the grid or outside it

if on the grid, behaviour  as noted 

but if off the grid will scroll to top briefly then return to where it was

**Comment by Greenlight88** [comment]
I think just with your senario you noted there maybe the filter not engaged? has to be turned on - I think it would happen if there was any kind of filtering at all manual or coded

**Comment by cortexrd** [comment]
I tried all I could: with or without an active user filter, scrolling down the page, leaving mouse in or out of grid, changing pages.
I just can't replicate any of the issues you're having.

I am on PC running Windows 10 Pro.  What are you using?  Did you try other platforms?

ND

**Comment by Greenlight88** [comment]
!! Youre right browser has an effect - Edge did not have the same issue - I use chrome and Windows 11

But i think I might have seen it do the same thing on windows 10

**Comment by Greenlight88** [comment]
Cleared cache on chrome and issue resolved - sigh sorry Norm
