### ISSUE TITLE
Sticky Group Headers are overlapping in grids

### ISSUE THREAD

**Issue by cortexrd** [cortexrd/Knack-Toolkit-Library#321]
In a grid with _sth and stickGroupingsWithHeader enabled, I have overlapping groups at the top of the grid, like this:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/b1e924c5-82a4-4b90-b0f0-8bb8cf27979b)

I tried all different options of row spacings and border/clean, but I always see this.

Also, the groups are transparent, which makes it difficult to read.

ND

**Comment by CSWinnall** [comment]
Hi Norm 
I will set up default colours to fix the transparency issue.  The stacking issue I will fix.

**Comment by cortexrd** [comment]
I made it work on my side, with custom code, so it should be easy to fix.  The tricky part will be to make it flexible so it adapts to all setups.

About the transparency, maybe try to use our new function: **ktl.core.mergeStyles**

**Comment by cortexrd** [comment]
All working well now - thanks!
