### ISSUE TITLE
_hc not working when col header has special character in it

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#323]
Hi Norm,

I was trying to use your ktl.views.hideTableColumns() function when, incidentally, the col header had a ? in it (Duplicate?). The column didn't hide, the thead.length is 0 as there are no matches for `$('#' + viewId + ' thead tr th:textEquals("' + header + '")')`, so the column doesn't hide.

I then went on to test hiding the same column using _hc, again this didn't work, I then tested with various other special characters and same issue arises.

Thanks
Amanda

**Comment by cortexrd** [comment]
Now I understand something that's been bothering me for a long time...
I've often been told that I was "_quite a special character_".
I guess that explains why I can't hide anywhere.  You guys keep finding me every time!

**Comment by cortexrd** [comment]
It's fixed in Dev code.
Test and close if all ok.

Norm

**Comment by amandajane-mo** [comment]
Hi Norm,

You're definitely a special character and my Duplicate? column is now hiding as expected.

Excellent
Thanks
