### ISSUE TITLE
Default UserPrefs

### ISSUE THREAD

**Issue by garinfrost** [cortexrd/Knack-Toolkit-Library#33]
These should always default to this:

userPrefs.showViewId = false;
userPrefs.showExtraDebugInfo = false;
userPrefs.showIframeWnd = false;
userPrefs.showDebugWnd = false;

Until the specific user Prefs are read and applied.

**Comment by cortexrd** [comment]
Hi Garin,

This has been fixed in release 0.11.13.
Please test, and close issue if all ok.

Thanks,
Norm
