### ISSUE TITLE
Have a CSS file in local environment.

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#336]
Hi Norm

Would it be possible to have a CSS file when we are in the local environment.  Would work exactly the same as the JS file in the KnackApps folder.

Craig

**Comment by cortexrd** [comment]
Hi Craig,

I think that should be possible.  

It would require some change to the KTL_Start.js file, and some way to wipe out the existing CSS from memory before applying the local one.  Otherwise, you'll probably end up with some conflict.

I'll try to find some time to experiment with this in the coming days.

Norm

**Comment by cortexrd** [comment]
Craig,

I found the solution!

I've implemented a first temporary in the **KTL_Start-dev.js** file for now:

![image](https://github.com/user-attachments/assets/b61d1cbb-89a0-4277-9397-24ed2e63e5dc)

Please confirm it's all working as expected, and I'll migrate to the official **KTL_Start.js**.

Norm

**Comment by cortexrd** [comment]
I've just pushed the Dev branch, if you're curious to see how I did it.  Was super simple!

**Comment by CSWinnall** [comment]
Hi Norm

Thank you for working on this.

When I run the KTL_Start-dev.js

I am getting this error:
'''
KTL_Start-dev.js:68 Uncaught TypeError: Cannot set properties of null (setting 'textContent')
    at loadKtl (KTL_Start-dev.js:68:66)
    at main.js?1724309427977&_=1724309427978:10:7
    at n (k_c5eb75a261ebc1642507163bce91e63c7ef994e4.js:2:3004564)
    at HTMLScriptElement.y (k_c5eb75a261ebc1642507163bce91e63c7ef994e4.js:2:3004663)
'''

It is Pointing to this line of code
'''
//Replace CSS from Builder by local file.
document.querySelector('#kn-custom-css').textContent = '';
'''

When I search the DOM for '#kn-custom-css' it returns nothing.

Not sure if this will help but in our app in the <head> our CSS file is loading here:

![image](https://github.com/user-attachments/assets/a2a421b0-5781-495a-9a52-d25a1d149078)

Thank you again for working on this.

Craig

**Comment by cortexrd** [comment]
Fixed!  Can you test it please?
Also pushed latest Dev.

**Comment by CSWinnall** [comment]
Thank you Norm works Perfectly
