### ISSUE TITLE
Undefined in SysOps Dashboard Message

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#342]
Hi Norm 

Not sure if this is an issue but I noticed this message when I first come to the Sysops dashboard on it's first refresh after a minute:

![image](https://github.com/user-attachments/assets/30702bc3-d777-4d3a-9542-432fefa2dc9c)

Craig

**Comment by cortexrd** [comment]
Put a break point at this line:
`const firstNameField = record[ktl.iFrameWnd.getCfg().acctFirstNameFld];`

And check the value of this:
`ktl.iFrameWnd.getCfg().acctFirstNameFld`

If all is ok, then I'll try to reproduce on my side, but in my apps, I don't see this bug.
Can you reproduce it on any machine?  Maybe I can see it here, in your app then.

ND

**Comment by CSWinnall** [comment]
Both first and last name are undefined

![image](https://github.com/user-attachments/assets/c1d0415d-9c4c-40f2-9bdd-4b7be93360c4)

**Comment by cortexrd** [comment]
Check these two lines, either by a breakpoint or executing them in the console (after setting accountsObj of course):

acctFirstNameFld: ktl.core.getFieldIdByName('First Name', accountsObj),
acctLastNameFld: ktl.core.getFieldIdByName('Last Name', accountsObj),

It is the **First Name** and **Last Name** that are off?  They must be exactly as spelled.

ND

**Comment by CSWinnall** [comment]
I don't have a field called First Name or Last Name I just have Name?
I have just reread your Wiki and can't find mention that Name needs to be split up.

![image](https://github.com/user-attachments/assets/9b643850-c12a-4bfa-af49-b91c592398e7)

![image](https://github.com/user-attachments/assets/9f8a711f-97c2-4534-94ed-5a39cf423f60)

**Comment by cortexrd** [comment]
You're right, I never noticed that.  All my projects have Name, but also First Name and Last Name.  

![image](https://github.com/user-attachments/assets/c63a191f-6420-4dde-852c-185651d14406)

This is convenient in my case because the last name is also used to define the data entry terminals and dashboards.  But most systems won't care about this.  So I should change this.

Norm

**Comment by CSWinnall** [comment]
Ok we will get those 2 fields added.  I think if it's not needed to be in 2 fields then that should be the default as that is Knacks default.  
Is it possible to get the first & last name direct from the field in the object?  Or split it using code?

I haven't looked at this I was just wondering.

**Comment by cortexrd** [comment]
The two fields should never be required or imposed.  The KTL should simply use the single Name field.

Even my own code didn't require them.  They were there for some other reason and I just happened to use them by accident.

>Is it possible to get the first & last name direct from the field in the object? Or split it using code?

No, too risky to split at the wrong place.  Some people have complex names.  And it's not possible to know from the field itself, you need a view render to get name.first and name.last.

Just add the two fields for now to get it working and I'll fix that when I come back from vacation.

**Comment by CSWinnall** [comment]
Ok will do.  Enjoy your vacation.
