### ISSUE TITLE
_ebo on a grid view breaks total row

### ISSUE THREAD

**Issue by CallumBoase** [cortexrd/Knack-Toolkit-Library#348]
When I enable bulk operations on a grid view that has a total row, the total row breaks.

https://github.com/user-attachments/assets/bcc634ab-f34b-49e4-aaff-48c109eb11fb

**Comment by CallumBoase** [comment]
@cortexrd I'm happy to try and fix this, but there's a lot of code related to `_ebo`
Can you point me in the right direction of what you think may be causing the issue to help me narrow down my search?

**Comment by CSWinnall** [comment]
Hi Callum
 I would suggest taking a look at line 6434:
 
![image](https://github.com/user-attachments/assets/6c5b619e-2ad6-4706-8f52-3f03e6f804e4)

This is where Norm deals with summaries.

I'd also check out **bulkOpsAddCheckboxesToTable** function as this is where he adds the checkboxes.  

The other function I would check is **fixTableRowsAlignment**.
Norm is away at the moment I hope this helps you narrow it down.

Craig

**Comment by cortexrd** [comment]
Hi guys,

I'm "sort of" back from vacation.  Officially it's Monday.

But @CallumBoase, I can give you a few pointers:

1. Try to move the Duration column elsewhere, including full left and full right to see if it has an impact.
2. If possible, add another column with a sum to see if it's ok.
3. Maybe it's related to the Duration field type that's not well supported.
4. Try to add a breakpoint to find when the data is modified, and by which function.

If you can give me access to that page it would be great, or any other similar page in that app.
If not, then just the live app's link might work.

You can reach me via Slack in a private msg for that.

Norm

**Comment by CallumBoase** [comment]
Hey @CSWinnall and @cortexrd 

Thanks for the pointers & suggestions. I haven't had a chance to take a look or play with it further yet.

@cortexrd I will slack you some details to take a look.

**Comment by cortexrd** [comment]
@CallumBoase,

I've found the root cause of the problem and a partial solution.  But that solution now breaks a lot of other stuff.
In other words... you opened a can of worms!!!

But that's ok, I'll find the ultimate solution eventually.

All this to say: Don't waste your time on it as it's a very complex issue, with race conditions, interacting features and conflicting events.

ND

**Comment by CallumBoase** [comment]
OK noted, thankyou!

**Comment by cortexrd** [comment]
Hi @CallumBoase,

Can you test the **beta** code please?
The issue should be solved now.
If so, please close this issue.

I will do a release in a day or two, after I'm done testing all I can.

Norm

**Comment by CallumBoase** [comment]
Hi @cortexrd 
That seems to be working fine for me now. Thanks so much, closing the issue
