### ISSUE TITLE
Using 24h time instead of am/pm

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#349]
### Discussed in https://github.com/cortexrd/Knack-Toolkit-Library/discussions/347

<div type='discussions-op-text'>

<sup>Originally posted by **Esther-00** September  2, 2024</sup>
I'm new to using the KTL and want to implement it in my app. 
However the default settings change the time input to am/pm values, but I want to keep using 24h time. 
My app currently uses military time (24h) on all time fields, but the KTL overrides this setting. 

I don't see an option to change this in the KTL configurator.
If anyone knows a how to do this has a script, it would greatly appreciated if you go share it with me.

Any and all help on this would be appreciated… 

Esther</div>

**Comment by CSWinnall** [comment]
Hi Esther

Welcome to the forum. I also noticed this a couple of weeks ago but didn't think that it was the KTL. You are right after disabling the KTL, it does appear to be editing the format of the time to am/pm. I believe Norm is away at the moment but he should be able to fix this when he gets back. In the meantime I will try and find the code that is doing this so he'll be able to fix it quickly.
Thank you for letting us know about this.

Craig

**Comment by cortexrd** [comment]
Can someone provide me with a sequence to reproduce the bug?
ND

**Comment by CSWinnall** [comment]
Hi Norm

It's a little weird.  We tend to use 24hr time and recently I noticed that all are time inputs were back to am/pm and I could not get them to change back to 24hr. I thought this was a knack bug but when Esther mentioned it, I disabled the KTL and the inputs were back to 24hr time.

Craig

**Comment by CSWinnall** [comment]
Morning Norm

Have you had any luck trying to find the cause of this?

Craig

**Comment by cortexrd** [comment]
No, I didn't have time yet.
But if you can provide me with a sequence to help me reproduce the bug, it would help a lot.
Just a short bullet list would do.  Maybe a few screen grabs too.

**Comment by CSWinnall** [comment]
Morning Norm

The time is always 12hr time and not 24hr time

Set a date field to 24hr view it on the front end its 12 hr format.  Even the fields in the iframewnd which have to be set at 24hr format.  Disable KTL it goes back to 24 hr format.  I have tried to find the issue in the ktl but no luck so far.

Frontend:
![image](https://github.com/user-attachments/assets/b53abda8-e3ba-47a5-a867-6e26ccac1417)

Backend:
![image](https://github.com/user-attachments/assets/e5ad8979-bfc6-4e2b-985e-8becb29b8ff6)

With KTL disabled Frontend:
![image](https://github.com/user-attachments/assets/9c67e653-c8ac-4033-bb2b-b8e31a138449)

Frontend:
![image](https://github.com/user-attachments/assets/2f7e960d-531f-4931-b01a-0e00ca7a29f1)

Backend:
![image](https://github.com/user-attachments/assets/92fe65e1-43f1-43c5-b134-b8c0481adefa)

Craig

**Comment by cortexrd** [comment]
I found the problem, but not the solution yet.
It's due to this code:

`$(`#${viewId} .kn-time`).timepicker().change(function (e) {
    processFieldChanged({ text: e.target.value, e: e });
})`

It handles the time change event, but also modifies the format unexpectedly.

**Comment by CSWinnall** [comment]
Great thanks Norm
