### ISSUE TITLE
_ha

### ISSUE THREAD

**Issue by gstark1234** [cortexrd/Knack-Toolkit-Library#351]
I love the header alignment matching to the column alignment. However, it doesn't work when I add a \<br\> to a long column header to break into 2 rows. Is there a way to fix this?

**Comment by CSWinnall** [comment]
Hi @gstark1234 

You are right the <br /> does stop _ha from working. We will look into this.

Craig

**Comment by cortexrd** [comment]
Hu guys,

I've fixed that in **Beta** if you want to test it.
I should do a release this week.

Norm

**Comment by gstark1234** [comment]
How do I test something in beta?

**Comment by cortexrd** [comment]
Here you go:  https://github.com/cortexrd/Knack-Toolkit-Library/discussions/186

**Comment by CSWinnall** [comment]
Great thank you Norm
