### ISSUE TITLE
_rlv Is not filtering a connection and selecting the date correctly

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#361]
Hi Norm

I am trying to use _rlv.  All the fields apart from 2 are working fine.  The 2 that are not are a Date field and a Connection field:

The connection field is stored fine in local storage and it is being selected but if the connection field is used to filter another field when it's selected it doesn't trigger the filter unless you change the field back to select then back to the right option.  This means that you cannot select an option in the field you are filtering.

The date field is is only saving the year and not the month & day.

![image](https://github.com/user-attachments/assets/acf26e16-3ffe-4f6e-b9ab-9ee0fbc7cd44)

Have you any ideas as to why this may be happening.

Craig

**Comment by CSWinnall** [comment]
Hi Norm
After some digging the ktlOnFieldValueChanged  (line 4032) is where the date field is being saved but instead of the text your function ktl.core.findLongestWord is being used in this case it returns 2024:

![image](https://github.com/user-attachments/assets/e7460cc5-c70c-4639-b1b2-4dfd00388785)

Hope this helps

Craig

**Comment by cortexrd** [comment]
Craig,

I am actively working on this now.  Should have a fix in the coming days.

ND

**Comment by CSWinnall** [comment]
Thanks Norm if you can figure out how to filter a connection
programmatically we will be very grateful. We haven't been able to do it
yet.

Craig
