### ISSUE TITLE
Have more than 1 developer named in the code.

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#37]
Hi @cortexrd 

Would it be possible to have more than one developer named in the code.  We have two developers who work together, and it will be useful to have the dev/prod switch button for both of us.

Cheers
Craig

**Comment by cortexrd** [comment]
Sure,

I've modified the code to accommodate that, and it will be in effect in next release today.

But it requires a bit of change in your new ktlReady initialization code:

```
window.ktlReady = function () {
    ktl.core.setCfg({
        developerNames: ['Firstname Lastname'], //Add your name here to get super powers!
    })
}
```

Note that **developerNames** is now plural!

Norm

**Comment by CSWinnall** [comment]
Thats Great thank you
