### ISSUE TITLE
_rlv Doesn't work in a modal

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#370]
Hi Norm

It appears that if a form is in a modal _rlv doesn't work.  I remember you turned persistent forms off for modals is there a way we can have persistent forms off but _rlv on in modals?

Craig

**Comment by cortexrd** [comment]
It's fixed in Dev now.  Test and close if all good.

**Comment by CSWinnall** [comment]
All Good Thank you
