### ISSUE TITLE
rlv Error in modals that don't have the keyword

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#376]
Hi Norm

Getting this error
Uncaught TypeError: Cannot read properties of undefined (reading '_rlv')
    at saveFormData (KTL.js:3718:88)
    at formContentHasChanged (KTL.js:3706:17)
    at KTL.js:21089:41

Pointing to this line
3718  - if (Knack.router.scene_view.model.attributes.modal && !ktlKeywords[viewId]._rlv) return;

Craig

**Comment by cortexrd** [comment]
Should be fixed now.
