### ISSUE TITLE
Disable SW Update

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#379]
Hi Norm

Is there a way to disable the sw update in KTL.  I have tried renaming the field. I haven't deleted it yet.  We just don't need or use it as it's too "aggressive".  Meaning that it interrupts users while they are working.  I have read through the wiki and I can't see anywhere we could stop the SW from checking the versions.  Whenever we update KTL I always get the message that I need to broadcast the update.

Craig

**Comment by cortexrd** [comment]
Found an elegant solution:  Simply rename the SW Update view to anything else, and the whole feature will be disabled.  No more warning, refreshes or anything.

But if ever you need it, just rename back to SW Update and you can push an update manually.

Best of both worlds!

Norm

**Comment by cortexrd** [comment]
I recommend, as a good practice, to rename to something explicit like "**SW Update (disabled)**"

**Comment by cortexrd** [comment]
Pull latest code again.  I just fixed the title search to enforce exact match.

**Comment by CSWinnall** [comment]
Amazing thank you
