### ISSUE TITLE
New line of Code is breaking the ktl dev tools and public filters lock

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#389]
Hi Norm

This line of code is breaking some buttons in the KTL in local code:
![image](https://github.com/user-attachments/assets/1774a705-0ba4-406c-a092-87874ce65425)

I can't click on the version info bar or the public filters lock.

Craig

**Comment by cortexrd** [comment]
Sorry about that.  Should be fixed now.
Pull Dev.

**Comment by CSWinnall** [comment]
Thank you
