### ISSUE TITLE
Suggestions for Keywords

### ISSUE THREAD

**Issue by cortexrd** [cortexrd/Knack-Toolkit-Library#39]
### Discussed in https://github.com/cortexrd/Knack-Toolkit-Library/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **CSWinnall** May 28, 2023</sup>
Hi @cortexrd,

Idea for a keyword.

_hcop Hide Column on Print
Will work exactly like your _hc keyword

or

_hfop - Hide Field on Print

Craig</div>

**Comment by Greenlight88** [comment]
Hi Normand,

I have a couple of ideas for key words which would make great additions for a wide range of users and use cases (and also me :))

**_rqi required if**

will change a field to required if other parameters on the form meet a set criteria - this would be super powerful. 

**_nri not required if**
will change a field to not required  if other parameters on the form meet a set criteria

To achieve the same effect in knack at the moment with no code you need to create three separate fields, one required, one not required and one that feeds off the other two - then set rules to make them appear or dissapear under certain conditions - bleh (This is not elegant)

**_uvc (suggested enhancement)** 

And just a suggested enhancement to an existing keyword - it would be amazing if the _uvc keyword would work out of the box with fields that have sub-values e.g. Name, Email, Address would be the main three

_Thanks Normand - love your work_

**Comment by cortexrd** [comment]
@Greenlight88 

Thanks, I take good note.

Norm

**Comment by CSWinnall** [comment]
Hi Norm

Suggestion:
Could you have a new keyword modifier maybe ktlScrnWidth (just a suggestion) which could have the standard width for mobile, tablet, desktop.  Then have custom sizes i.e. 1000px.

For example

_style=[font-size: 14px], [ktlScrnWidth, mobile], [ktlTarget, scene]
_style=[font-size: 16px], [ktlScrnWidth, 1000px], [ktlTarget, scene]

Amanda

**Comment by cortexrd** [comment]
Hi guys - Craig and Michael,

Can you do me a favor please?  I'd like you to re-create your requests in the [Requests for Keywords section here](https://github.com/cortexrd/Knack-Toolkit-Library/discussions/36)

After that, I will delete this section to avoid redundancy.

Thanks,
Norm

**Comment by cortexrd** [comment]
Closing this issue.

In the future, when you have ideas and request, please create a new **Discussion** with Category **Ideas**
Direct link here:  https://github.com/cortexrd/Knack-Toolkit-Library/discussions/new?category=ideas

Thanks :)
Norm

**Comment by cortexrd** [comment]
> Hi Normand,
> 
> I have a couple of ideas for key words which would make great additions for a wide range of users and use cases (and also me :))
> 
> **_rqi required if**
> 
> will change a field to required if other parameters on the form meet a set criteria - this would be super powerful.
> 

Hi Michael - @Greenlight88,

I've just completed a first attempt at the long-awaited **_req** keyword.

See the documentation here:  https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Keywords#_reqfield1-field2

You can try the Beta code as a sneak preview, and give me your feedback.

Cheers,
Norm

**Comment by Greenlight88** [comment]
Hey Norm - I just saw this comment - Thank you so much its great and works as intended - it does avoid the need to keep two fields in knack (required and not required), set their visibility in some way  and then a third formulae field to collate the results and then all kinds of issues if you need to update so thank you - I think it solves about 80% of it you still need to have child pages to a form if you want to update based on values entered on the form - but this can flow naturally in a lot of cases anyways. I can imagine how complicated it would be to get it to work in form dynamicaly  I use another form software - cognito forms  - which have this kind of thing working - you can set each of the fields 

Default value
Visibility
Required property

based off formulaes that can be quite complex and refer to other fields that are live. They have a builder come up that is sort of lile the filter pop up on knack to implement these 

Awesome stuff, thank you
