### ISSUE TITLE
Bulk Action only updating first row

### ISSUE THREAD

**Issue by shedancesunderthemoon** [cortexrd/Knack-Toolkit-Library#393]
Hi! I'm using the _click keyword to create a bulk action, but it only seems to be updating the first row in my Grid. The Entire Action Link column will highlight in Green and it will update the first record and then will add a "STOP" after the verbiage on my button, but nothing ever happens. I've left it alone for 30 minutes and still no additional updates. I tried it elsewhere on a really simple table and it worked perfectly. Is it really just going that slow? Do I need to wait for the STOP to go away? Thank you and appreciate all your work here. I only just discovered this and it's quite amazing!!

**Comment by CSWinnall** [comment]
Hi @shedancesunderthemoon 

How many records are you trying to run the _click on?

The more records you run the longer it takes.  I would run it on 50 records for reasonable speed and 100 at most.  Knack refreshes the view after every action.

I would also suggest using Bulk Action rather than _click I find it works a bit smoother.

Craig

**Comment by shedancesunderthemoon** [comment]
It's only 9 records in that view right now. I tried it on yet another page and it also worked totally fine. I'm beginning to wonder if maybe it was something I did the first time I ran it. That time, I only added the first parameter, i.e. _click, Send Now. When I got into the page, it immediately asked me if I wanted to auto run it and I said no as I wasn't ready for the action yet. Is it possible it placed a cookie or something that is prohibiting it from running through the whole process?

**Comment by CSWinnall** [comment]
Ok try adding confirm instead of auto that way when the page opens you should get that message again.

**Comment by shedancesunderthemoon** [comment]
I did that, and it does ask me that question again, but then only updates the first record

**Comment by shedancesunderthemoon** [comment]
Just tried it again and the pop up says "Proceed with auto-click on Send Now?"

**Comment by shedancesunderthemoon** [comment]
Just re-read your first comment again. What do you mean by use Bulk Action instead?

**Comment by shedancesunderthemoon** [comment]
Figured it out! I just had to add Bulk Action to the User Roles and boom it worked! So easy. Thank you!!!

**Comment by CSWinnall** [comment]
I'm glad you've got it sorted.

If you don't want the check boxes on every table with a action link.  you can use _ebo=action on the grid and remove the user role Bulk Action.

If you want it for specific user roles

_ebo=[action], [ktlRoles, Developer]

This will only allow users with the developer role to be able to use bulk action on the grid.

Craig

**Comment by shedancesunderthemoon** [comment]
Thank you Craig! Appreciate it!

**Comment by cortexrd** [comment]
Hi guys,

Thanks Craig for the nice support.

@shedancesunderthemoon, I'd like to clarify why the _click was only processing the first record.

When I do the action, I take note of the currently processed record ID, so I don't process it again on next view render.  This is necessary to avoid getting caught in a loop.

So, when it's time to process the next record with the action of interest, if it has the same record ID as the one I just took note of, I just sit there and wait until the action has finished doing its thing, as this will trigger a view render, which in turn, will kick off the next cycle of the keyword's sequence.

This is why I added this in the documentation:

**_Important: It is crucial to properly filter your view to exclude any records that should not be clicked. Additionally, configure your Action to reset a value in a manner that prevents triggering an endless clicking loop._**

To achieve this, you must add a Yes/No field in the table that tells the _click command that it's been executed.  Default is No, and it will be set to Yes when clicking on it. Also hide the action when Yes.

This is what it looks like:

![image](https://github.com/user-attachments/assets/7d3247f5-c414-456c-9bcb-c6dff86df36f)

That flag is called "Yes/No Dropdown" in my example.

I realize now that the documentation needs to be clarified!

Thanks for reporting,
Norm

**Comment by shedancesunderthemoon** [comment]
Thank you Norm! Really appreciate all your work on this!

**Comment by shedancesunderthemoon** [comment]
I do have another, sort of, related question. Is there a bulk add function? Like bulk inserting connected records from a form? Right now, I can only add one connected record at a time.

**Comment by CSWinnall** [comment]
> I do have another, sort of, related question. Is there a bulk add function? Like bulk inserting connected records from a form? Right now, I can only add one connected record at a time.

No there is not an option to do this in the KTL.  If you can start a discussion and lay out what you want and how you see it working then we might be able to add it.

I am closing this issue if you have any further issues with this then reopen it.

Thanks Craig
