### ISSUE TITLE
Can't get code loaded properlly

### ISSUE THREAD

**Issue by gstark1234** [cortexrd/Knack-Toolkit-Library#398]
Hi Normand!

I have used KTL in my previous app, but for some reason every time I try to add it to my new app it causes my JS to not work.  Any way we can hop on a quick Zoom for me to show you what's happening?

**Comment by cortexrd** [comment]
Hi Gary,

I'm super busy these days, so I won't have time for a zoom until at least a week.

But if you send me the link to your app with a login to any page, I can try to see what's happening.

Also:
1. did you look at the console logs?
2. when you say "...causes my JS no not work", what do you mean exactly?  Does some parts of your code work properly, but not all, or the whole app doesn't even launch?

Any additional information will help,
Norm

**Comment by gstark1234** [comment]
Hey Normand,

I cleaned up my JS and it's working now :)

Thank you again for this awesome platform!  Have a great weekend!

Gary
