### ISSUE TITLE
How to reverse Bypass KTL

### ISSUE THREAD

**Issue by MickGraham23** [cortexrd/Knack-Toolkit-Library#403]
I inadvertently clicked on Bypass KTL and I now cant get it to work again.
How do I reverse this?

rgds
Michael

**Comment by chprojectsupport** [comment]
I think you just close your browser session and start again. Carl HolmesOn 3 Nov 2024, at 10:21, MickGraham23 ***@***.***> wrote:﻿
I inadvertently clicked on Bypass KTL and I now cant get it to work again.
How do I reverse this?
rgds
Michael

**Comment by amandajane-mo** [comment]
Hi Micheal,

If you shut your Knack tab and reopen ktl should be up and running.

Amanda

**Comment by MickGraham23** [comment]
Simples - Thanks...

I was reluctant to do that with my 35 tabs open lol!

**Comment by cortexrd** [comment]
Actually, this feature is applied on a "per-tab" basis.  So, if you have 35 tabs with the KTL running and you disable it for one of them, and the 34 remaining will still be running the KTL.

You only need to close and re-open the one that's been disabled.

I will emphasize that in the documentation.
