### ISSUE TITLE
🚨 KTL Not Loading

### ISSUE THREAD

**Issue by kukuk52** [cortexrd/Knack-Toolkit-Library#407]
Apps with KTL are no longer loading and users are only getting blank pages. Please advise

**Comment by cortexrd** [comment]
I know, I'm on this now.  Knack has changed something.

**Comment by ecwate1** [comment]
I'll add that we have one app that is heavily using the KTL that is affected by this but another app that is using the same KTL features that is working as expected.

**Comment by cortexrd** [comment]
To all those affected by this issue:

The KTL v0.29.2 has a hotfix.

You'll need to do a **forced refresh** by pressing Ctrl+F5 (or Ctrl+Shift+R) to get the latest code.
You can also clear your cache if that doesn't work.

Norm

**Comment by ecwate1** [comment]
@cortexrd We currently have a version of the KTL prod branch on a web server and pulling it from there in our Knack apps. We're looking to get a most recent version including this hotfix, but it appears the only one available at the moment is the dev branch, so I had a quick question - How stable is the dev branch at the moment?

**Comment by universenz** [comment]
Thanks for patching this issue so quickly. When you get time, I would be keen to understand what they changed and whether or not you think Knack should have at least one application in their test suite that has KTL implemented. Breaking changes like this look bad for Knack and they're bad for business.

**Comment by kukuk52** [comment]
Thanks for the quick fix.

**Comment by cortexrd** [comment]
> Thanks for patching this issue so quickly. When you get time, I would be keen to understand what they changed and whether or not you think Knack should have at least one application in their test suite that has KTL implemented. Breaking changes like this look bad for Knack and they're bad for business.

Yes, I perfectly agree.  We need to establish a protocol for them to tell me (at least) and all other coders out there, when and what they will change... BEFORE they change it.

I'm very grateful that it was a quick and easy for this time. And that I was available to do it now.  Imagine if I was out of town far away in vacation and without Internet.

**Comment by cortexrd** [comment]
> @cortexrd We currently have a version of the KTL prod branch on a web server and pulling it from there in our Knack apps. We're looking to get a most recent version including this hotfix, but it appears the only one available at the moment is the dev branch, so I had a quick question - How stable is the dev branch at the moment?

@ecwate1 I've just released and pushed the Prod branch.
The Dev branch is stable.  Morbern have been using it for several weeks already without issues.

**Comment by cortexrd** [comment]
**For those interested in understanding the technical reason why the KTL broke**

Until about an hour ago, I was using **Knack.mixpanel_track** object to get the **account name** and **app name** that are used in various places.  This was being read right at startup, which explains why we had a white screen.

This object **doesn't exist anymore** - for some reason.

After a bit of research, I found out that the information was available elsewhere: in the **Knack.app.attributes** object.

Looking back, it's easy to say that I should have chosen that one in the first place.  But who knew!?

Now what's next!!!??

Norm

**Comment by donkingjedi** [comment]
Ctrl-F5 worked great for me, but it's not feasible to notify all our external users. How do I get it live for them?

**Comment by cortexrd** [comment]
> Ctrl-F5 worked great for me, but it's not feasible to notify all our external users. How do I get it live for them?

This is due to the way the browsers implement the cache.  They can't know that the code has changed and need to wait until the cache expires before really downloading it again.  This is to optimize the user experience and make things appear faster.

But I understand your point, I have the same problem with my clients.
I'm desperately trying to find a solution to this.

Norm

**Comment by universenz** [comment]
@cortexrd glad to see you were able to find the issue. I fear that with the proposed regular updates from Knack, this may become a more regular occurrence. I've made the recommendation for Knack to include the library in at least one of their test apps in the test environment just to make sure there are no app breaking changes published again in the future (without at least giving you a heads up first).

https://forums.knack.com/t/request-for-knack-developers-regarding-ktl-library/18165

**Comment by cortexrd** [comment]
To bypass the cache and avoid having to tell everyone to do Ctrl+F5, try to modify your loader to include the question mark like this:

```
KnackInitAsync = function ($, callback) { // Load the Knack Toolkit Library (KTL)
    (window.LazyLoad = LazyLoad) && LazyLoad.js(['https://ctrnd.s3.amazonaws.com/Lib/KTL/KTL_Start.js?123456'], () => {
        loadKtl($, callback, (typeof KnackApp === 'function' ? KnackApp : null), '' /*KTL version, leave blank to get latest*/, 'full'/*min or full*/);
    })
};
```

In other words, add this:   **?123456**

The the KTL_Start.js filename.

This may work.  I can't test it unfortunately, but it won't break anything.

Norm

**Comment by godfredbrown** [comment]
@cortexrd adding this: ?123456 actually worked.
Thanks a lot.

**Comment by donkingjedi** [comment]
Worked for me too. Thanks Norm!

**Comment by cortexrd** [comment]
Wow, that's so cool!!!  I finally found a solution that plagued me for so long.

Thanks for testing on my behalf.  I couldn't test because all my code was already in the cache and there wasn't anything to update.

What this does is simply tell the lazyLoad to fetch the file between the two single quotes:
`'https://ctrnd.s3.amazonaws.com/Lib/KTL/KTL_Start.js?123456'`

Since that string is new compared to last execution, it forces the re-downloading of the KTL_Start.js file instead of using the one from the cache.  The **?123456** is a dummy parameter that is legal syntactically but not used (ignored).

If ever you have the same issue someday, you can change it to **?234567**, or **?202411121423** (date/time stamp) or anything else - as long as it changes.

Norm

**Comment by godfredbrown** [comment]
Thanks for the explanation.
I am definitely keeping this in mind.

**Comment by CSWinnall** [comment]
When we use code on a server on our dev branch we use 

URL + '?' + Math.random();

This will always make sure you have the latest code.

On our prod branch we will use

URL + '?v=1'

Then we increment when we push code.

**Comment by CSWinnall** [comment]
With KTL

We use Norms version numbers.  We wait for a prod release then increment the KTL version number.  This way we do not have a cache issue.

Craig
