### ISSUE TITLE
Hide/Show filter buttons

### ISSUE THREAD

**Issue by gstark1234** [cortexrd/Knack-Toolkit-Library#409]
Hi Norm!

Here's a short video that shows the hiding/showing of the filter buttons based on whether a filter has been applied. Can that be integrated into KTL in any way so I can apply it to all views?  

https://www.loom.com/share/40a880fd6f014e8180f035c5dbdd945d

Here's the code: 
/* Hide / Show KTL filter buttons */
$(document).on('knack-view-render.view_12114', function () {
  console.log('view_12114 has rendered. Setting up dynamic filter visibility.');

  // Function to check the filter status and toggle visibility
  function toggleFilterControlVisibility() {
    const currentURL = window.location.href;

    // Determine if filters are active
    let isFilterActive = currentURL.includes('filters=') && !currentURL.includes('filters=%7B%7D');

    // Select the filterCtrlDiv
    const filterCtrlDiv = $('.filterCtrlDiv');

    if (filterCtrlDiv.length > 0) {
      console.log('filterCtrlDiv is present.');
    } else {
      console.log('filterCtrlDiv not found.');
    }

    // Always hide the Stop Filter button
    const stopFilterButton = $('#kn-report-view_12114-1_Stop_filterBtn');
    stopFilterButton.css({
      display: 'none',          // Hide from layout
      visibility: 'hidden',     // Ensure it’s not visible
      pointerEvents: 'none',    // Disable interactions
      width: '0',               // Collapse width
      height: '0',              // Collapse height
      overflow: 'hidden'        // Prevent any content from spilling out
    });
    console.log('Stop Filter button is fully hidden.');

    // Toggle visibility of the Save Filter button based on filter status
    const saveFilterButton = $('#kn-report-view_12114-1_Save_filterBtn');
    if (isFilterActive) {
      saveFilterButton.css({
        visibility: 'visible',  // Show the button
        opacity: '1',           // Ensure it's fully visible
        backgroundColor: 'transparent', // Remove yellow background
        border: 'none'          // Remove the border
      });
      console.log('Save Filter button is visible with updated styling.');
    } else {
      saveFilterButton.css({
        visibility: 'hidden',   // Hide the button but keep it in the DOM
        opacity: '0'            // Make it fully transparent
      });
      console.log('Save Filter button is hidden because no filters are applied.');
    }
  }

  // Initial check on render
  toggleFilterControlVisibility();

  // Monitor changes to the DOM (filters being added/removed)
  const targetNode = document.querySelector('#kn-report-view_12114-1');
  const config = { childList: true, subtree: true };

  const observer = new MutationObserver(() => {
    console.log('DOM mutation detected. Rechecking filter status.');
    toggleFilterControlVisibility();
  });

  if (targetNode) {
    observer.observe(targetNode, config);
    console.log('MutationObserver attached to #kn-report-view_12114-1.');
  } else {
    console.log('Failed to attach MutationObserver. Target node not found.');
  }
});

**Comment by cortexrd** [comment]
Hi @gstark1234,

I've made an update that does what you need: hide the filter buttons unless there's an active filter.

You need to override the default behavior by adding these lines of initialization in your code:

```
ktl.userFilters.setCfg({
    autoHideButtons: true,
})
```

Add them inside the window.ktlReady function, somewhere between the two **//KTL Setup** tags.
See here for details:  https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Customizing-Features#customizing-features-1

![image](https://github.com/user-attachments/assets/2182ccec-638e-43f0-88b8-afd08d1b895b)


You can test the **Beta** code for now.

Don't forget to remove your own code to see the actual effect!

One last detail: the pink [X] button is useful when you have a complex filter with several fields, and you want to clear them all at once.

Norm

**Comment by cortexrd** [comment]
I've also added the flag to have monochrome buttons, based on your code sample.

```
ktl.userFilters.setCfg({
    autoHideButtons: true,
    monochromeButtons: true,
})
```

Beta code has been updated.

Norm

**Comment by gstark1234** [comment]
Thank you, Norm!

I removed my code and added yours. The code worked at hiding/showing the
buttons - GREAT! THANK YOU!!

An odd thing also happened after implementing the new code - my table that
is on the same page changed from no outer border (pre-KTL update) to an
outer border (post-KTL update). Not sure if it matters, but this table's
filtering is affected by _ft on the 1st pivot table on the same scene.

Here's an image of what I'm talking about - you can also see that this
table is impacted by the change, as the save buttons are visible in the 1st
image but not in the 2nd image. Any idea why that happened?  Thank you
again for your help!!!!!

PRE-KTL UPDATE
[image: image.png]
POST KTL UPDATE
[image: image.png]

**Comment by cortexrd** [comment]
@gstark1234,

Glad you like it.

About your issue with borders appearing..., unfortunately I can't see any image.
I think you made a typo with **_ft**.  There's no such keyword.

Try again,
Norm

**Comment by gstark1234** [comment]
Thank you again, Norm! Your responsiveness is amazing!

How long do I need to keep it in beta to preserve the new filter options?

Also, here's a short video to show you the table border quirk:

*Filter options / table borders* - Watch Video
<https://www.loom.com/share/690fe9b30a42492da88f99c01732c2cc>
<https://www.loom.com/share/690fe9b30a42492da88f99c01732c2cc?utm_medium=gif>

**Comment by gstark1234** [comment]
Had to take it out of beta, as it's also affecting the layout of other
unrelated tables - you can see here:

*Borders* - Watch Video
<https://www.loom.com/share/e0b845ce96a84949934349eb1fecc8c8>
<https://www.loom.com/share/e0b845ce96a84949934349eb1fecc8c8?utm_medium=gif>

**Comment by cortexrd** [comment]
Very clear now - thanks.

I'll need some time to reproduce the bug somehow.  

Otherwise, if possible, can you give me access to one of those pages where the bug occurs?  I have your link, but the login is expired.  You can send me the info by email.

**Comment by gstark1234** [comment]
Sure. What's your email, and do you need builder access or just live app
access?

**Comment by cortexrd** [comment]
Just the live app.

**Comment by gstark1234** [comment]
Hi Norm!I sent you the info at ***@***.*** If you need anything else, just let me know.Gary StarkValio, Founder & ***@***.*** Nov 19, 2024, at 3:12 PM, Cortex R&D Inc. ***@***.***> wrote:﻿
Just the live app.

**Comment by cortexrd** [comment]
@gstark1234,

Can you try the new Beta please?  Ctrl+F5.

Norm

**Comment by cortexrd** [comment]
BTW, whenever you see something wrong like this or a long spinner, always check the console logs.
This usually saves a lot of time. (F12 or Ctrl+Shift+i)

**Comment by gstark1234** [comment]
Working great now in Beta!! I didn't even have to add the code below!

ktl.userFilters.setCfg({
    autoHideButtons: true,
    monochromeButtons: true,
})

Thank you so much! What do I do now regarding beta and the production
mode? In other words, do I keep it in beta until you tell me to move
to Production?

Thank you again!!

**Comment by cortexrd** [comment]
Great, but the two flags are supposed to be there!
I don't understand how this can work without them...

**Comment by cortexrd** [comment]
I've just release 0.29.3 a second ago.
You can just go back to Prod (default)  
No version number in the loader.

**Comment by gstark1234** [comment]
Oh...they were still there from the other day :) sorry about that!

How long do I stay in beta now?

**Comment by gstark1234** [comment]
I just changed from b to p and now the filter buttons (the ones that the
new code hides if not filtered) are showing. The version showing in the
upper right is

V1.0.0 KTL v0.29.2

**Comment by cortexrd** [comment]
You're not at the right version.  You have two options for force using the new code:

1. Ctrl+F5 to bypass the cache.  But all other users would have to do the same, unles their cache expires - and that can be in several hours.
2. Add **?1234** at the end of your loader's **KTL_Start.js** - see image.

![image](https://github.com/user-attachments/assets/bbf4c7fe-dda5-4d0a-a65e-b39d9d2c5aa0)

Actually, any random number will work, as long as it changes when you need to force the update, in a future release.
This is a trick to go faster, without haing to wait until the cache expires.

*But leave out the 0.29.2 part between the single quotes otherwise you'll frozen to that version (as in my case).

ND

**Comment by gstark1234** [comment]
OK...I added ?1234 and it's working great! Do I just keep it there moving
forward?

**Comment by cortexrd** [comment]
Yes, you can leave it there until you have the same issue, then change it to ?2345 or ?abcdxyz  doesn't matter what's after the question mark, but not space or funky chars.

**Comment by gstark1234** [comment]
Got it. Thank you so much...it's working great!!

**Comment by cortexrd** [comment]
Hi to all,

I've update the loader to always bypass the cache no matter what.  Since the start file is so small, this will not add any perceptible delay, and the benefits will be tremendous.

This means that no one should ever need to use the Ctrl+F5 trick anymore.  Just any regular refresh you're used to will always fecth the latest code.

Go get it here:  https://github.com/cortexrd/Knack-Toolkit-Library/blob/dev/KTL_Loader.js

And overwrite the one you have in the Builder.

For those who have locked the KTL version, don't forget to put back that number between the two single quotes.
Also the **minified** or **full version** of the code (min/full).

![image](https://github.com/user-attachments/assets/e1d70d37-5fef-4773-8ac5-6c28fcd91743)


Norm
