### ISSUE TITLE
_sth Background Colour

### ISSUE THREAD

**Issue by HugoCox5HC** [cortexrd/Knack-Toolkit-Library#414]
Is there a way to add a background colour to a header when using sticky headers?  Currently using just _sth the background is clear so it is difficult to read the column headers when there are populated rows scrolling up behind the header. 

Thanks a lot and loving the KTL as ever!

![2024-11-26 09_12_00-Order Management Platform](https://github.com/user-attachments/assets/06cc1576-559d-4f83-a487-036a957622ed)

**Comment by CSWinnall** [comment]
Hi Hugo

If you add this CSS to your builder CSS pane


`
#knack-body table > thead > tr > th{
        background-color: white;
        color: black;
    }
`

This will change the background colour and the text colour.  Change the colours to suit your app.

Craig

**Comment by HugoCox5HC** [comment]
Thanks Craig,
that works for the text colour, but didn't seem to change the background colour.  I changed it to  
`#knack-body table > thead > tr > th{ background-color: white !Important; color: black; }` and it looks to be working.  Thanks!

**Comment by CSWinnall** [comment]
No Worries

Can you try this selector without the !important:
`#knack-body .kn-content .kn-view table > thead > tr > th`

I always try not to use important where possible.

Craig

**Comment by HugoCox5HC** [comment]
Hi Craig,

Just tried it without the !Important and it went back to being transparent (but the text colouring worked).

Thanks
