### ISSUE TITLE
Different Ktl versions showing on Mobile and Desktop

### ISSUE THREAD

**Issue by SteveRobinson-FIShR** [cortexrd/Knack-Toolkit-Library#417]
Hi All

I have recently been advised by my mobile team that they are receiving a message prompt to update their version of ktl.  I have always managed to sync this successfully in the past however when I log in on my mobile the version shown is KTL 1.0 29.4 and KTL 1.0 29.3 on my desktop.  In the past I would typically notice the change on my desktop first and then adjust and broadcast the update, however my desktop seems to be stuck to version 29.3.

Any help appreciated.

**Comment by SteveRobinson-FIShR** [comment]
Hi All

I have tracked down the error and as suspected it was the different versions.  I need to do a hard reset on my desktop to get the version to update to KTL 1.0.0 29.4 and then was able to reset and broadcast using the sys op dashboard.

**Comment by SteveRobinson-FIShR** [comment]
Closed

**Comment by cortexrd** [comment]
Hey Steve,

One other thing that can cause such a problem:  once in a while, when you update the Javascript code and save it, **it doesn't actually save it**.  This is an old bug in the Builder.  

The solution is to type in a dummy space at the end and save again.

Could that be your case here?
Did you do a Ctrl+F5 to bypass the cache?

Also you should use the new loader that does that automatically:  https://github.com/cortexrd/Knack-Toolkit-Library/blob/dev/KTL_Loader.js

with the added `?${new Date().valueOf()}`

Norm

**Comment by SteveRobinson-FIShR** [comment]
Thanks Norm

The toolkit is an amazing asset, and I greatly appreciate the work you and others have put into it.

There are so many features that I am not using yet but I am slowly working my way through my app and making adjustments.

Kind Regards

Steve Robinson

[A logo for a fish company  Description automatically generated]


Steve Robinson
CEO - Founder
PHONE  0499 523 856
Email    ***@***.******@***.***>
Web       www.fishr.net.au<http://www.fishr.net.au/>


Let’s make flexibility work - if you receive an email from me outside of business hours, I am sending it at a time that works for me. I’m not expecting you to read or reply until normal business hours.

FIShR acknowledges the traditional owners of country throughout Australia and their continuing connection to land and community. We pay our respect to them and their cultures, and to elders past and present.
