### ISSUE TITLE
Undefined Bulk Operation Error

### ISSUE THREAD

**Issue by HugoCox5HC** [cortexrd/Knack-Toolkit-Library#420]
Hello,

where should i look to resolve this error message?  I don't know where to start.  It used to work but stopped very recently (some changes have been made recently).
![image](https://github.com/user-attachments/assets/cd134bc9-d9dd-4a81-9180-fc421a10791f)

Thank you!

**Comment by cortexrd** [comment]
I am working on this right now actually.  It's an issue related to a recent Knack change.
Norm

**Comment by HugoCox5HC** [comment]
Thanks Norm!

**Comment by cortexrd** [comment]
Should be fixed now in **v0.29.5**
Also, don't forget to get the latest loader to bypass the cache.
https://github.com/cortexrd/Knack-Toolkit-Library/blob/dev/KTL_Loader.js

**Comment by HugoCox5HC** [comment]
Thank you!
