### ISSUE TITLE
Setting up iFrameWnd

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#44]
Hi Norm
I have been trying to setup the iFrameWnd I have followed the instructions on GitHub but when I try to submit the from with all 4 checkboxes ticked it won't keep them ticked and I get this error every time I tick a box:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/2a13e9a0-5b09-427e-9782-cc945a95ce98)

Any ideas?

Craig

**Comment by cortexrd** [comment]
It's the acctPrefsFld variable that is probably empty, being itself set from this variable: acctUserPrefsFld.
Whcih is set with: 

`acctUserPrefsFld: ktl.core.getFieldIdByName('User Prefs', accountsObj),`

Check if your main accounts object is named "Accounts" or something else.  When it has a different name, as I've seen in some apps, you need to override the default name using this in your ktlReady function:

```
ktl.iFrameWnd.setCfg({
    accountsObjName: 'Accounts', //If your main accounts table is not "Accounts".
});
```

If all looks good, you can create an temporary account for me so I can single-step it.

Norm

**Comment by cortexrd** [comment]
Craig,

1. I see that your object is indeed "Accounts" as per default, so that's not the problem.
2. Can you switch to **full** code instead of minified please?  It's very hard to read!
3. Also, please add my name to the developerNames list.
4. I am trying to access the Dev Options pop-up, but can't.

**Comment by CSWinnall** [comment]
Hi Norm 
I have done these things.
Craig

**Comment by cortexrd** [comment]
This line in your Javascript pane:

ktl.iFrameWnd.setCfg({accountsObjName: 'AppUsers'});

Should match you Accounts table:

ktl.iFrameWnd.setCfg({accountsObjName: 'Accounts'});

Norm

**Comment by cortexrd** [comment]
Also, don't forget to set **all** your forms to auto-reload in the iFrameWnd.

_"Set the view title to Update User Prefs. Enable the form's auto-reload in the Submit rule."_

**Comment by CSWinnall** [comment]
I have done this too.

We can meet any time after 11.30am our time which I think is 7.30am your time

**Comment by CSWinnall** [comment]
> This line in your Javascript pane:
> 
> ktl.iFrameWnd.setCfg({accountsObjName: 'AppUsers'});
> 
> Should match you Accounts table:
> 
> ktl.iFrameWnd.setCfg({accountsObjName: 'Accounts'});
> 
> Norm

Hi Norm

This has fixed the issue.

Craig
