### ISSUE TITLE
Issue using ktlSel, page

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#55]
Hi Norm

The issue with using the page selector is that when you navigate away from the page where you put the keyword it doesn't remove the css as the #knack-body never re-renders until you refresh your browser.

I applied _zoom to a page and it was still applied when I navigated away.  I fixed this by attaching it to .kn-scene which does re-render when you navigate away.

Craig

**Comment by cortexrd** [comment]
I fixed this issue in 0.13.6.

Here's what I did:

1. changed the `[ktlSel,page]` selector to apply to **.kn-content**
2. added a scene selector `[ktlSel,scene]`, that applies to the all views, i.e. same as page, but excluding the top menu.

Thanks for reporting the issue,
Norm

**Comment by CSWinnall** [comment]
Perfect Thank you Norm
