### ISSUE TITLE
Inline Edit - Failed waiting for cell editor

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#58]
Hi Norm,

I'm receiving the following error message when doing an inline edit on a table (simple yes/no radio buttons):

<img width="1267" alt="Cell Editor Error" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/2525ebd0-d957-4487-a0b8-57412e4e7dd7">

Which points to this code in **KTL-0.13.4.js**:

```
//Work in progress:  When user clicks on a cell for inline editing, provide a method to change its style, to make it wider for example.
            if (e.target.classList) {
                if (e.target.closest('.cell-edit')) {
                    ktl.core.waitSelector('#cell-editor .kn-input')
                        .then(() => { ktl.fields.ktlInlineEditActive(e); })
                        .catch(err => { console.log('Failed waiting for cell editor.', err); });
                }
            }
```

Once this error occurs Knack _seems_ to slow right down (subjectively). I've tried to generate this error on other pages with other inline edits to no avail, the page the error occurs on is very busy. The error does not occur every time I submit an inline edit.

Any ideas?

Thanks,
Amanda

**Comment by cortexrd** [comment]
I increased the default timeout for the waitSelector function from 2 to 5 seconds.
I hope this will work for all scenarios.

I will close the issue, but feel free to re-open if you still see the problem,
Norm

**Comment by amandajane-mo** [comment]
Hi Norm,

Thank you, haven't had the error reoccur, I'll keep am eye out for it.

Amanda

**Comment by amandajane-mo** [comment]
Hi Norm,

The failed waiting for cell editor issue has reappeared. We tried increasing the timeout to 10 seconds, but the error still occurred.

Any help appreciated, thanks,

Amanda

**Comment by cortexrd** [comment]
I've added support for the Rich Text class redactor-editor in the waitSelector.
Please test and let me know if it's works.

Norm

**Comment by amandajane-mo** [comment]
Hi Norm,

Thank you, I haven't had the issue reoccur in rich text fields while in dev mode. 

We are still getting the error on occasions when editing other field types inline, we think this happens when we have other 'stuff' going on, i.e. an api calls and Knack being slow. We are making some changes to our code which we think may improve things. As all views on the page are re-rendered whenever an inline edit is submitted any api calls on said views are running again, when we don't really need/want them to. 

I'll keep you posted with any updates.

As an aside I've just starting experimenting with **_cfv** and I love it.

Thanks
Amanda
