### ISSUE TITLE
Events listeners not working on number inputs when in modal

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#59]
Hi Norm,

We have an issue with an **on blur event not working** on a number input, the problem only arises if the form is opened in a modal and only effects number inputs. We've turned the KTL off on our backup app and the listener works as expected. It's a simply number validation:

![Screen Shot 2023-06-22 at 13 08 13](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/6f44e8b7-9fd0-42c6-ac93-d100029d7f8c)

We're not getting any errors and if we engage with the input very quickly the listeners works as expected. We've tried adding different listeners to other number inputs and the same issue arises.

Any ideas?

Thanks
Amanda

**Comment by cortexrd** [comment]
Hi Amanda,

I'm not sure I understand.  On my side, I tried a modal page that has numeric fields and the validation works fine.

Can you give me access in page that has the problem in your backup app, so I see it?
Don't forget to give the the URL for direct access, so I don't search around - you guys have a big app!

I'd like to know...
1. what are the actions you make
2. what are the problems you see
3. what you'd expect to see

Norm

**Comment by amandajane-mo** [comment]
Hi Norm,

Should have been clearer, we're not 100% sure this is a KTL issue, just when we ran the same page/code on our backup (with no KTL the code worked as expected). We're not using KTL validation on this page, we set it up before we started using KTL. 

Here is the link:
https://arcproject.knack.com/arc-beta#debug/

If you click on an **Add Top** link from the grid, you'll see the popup in question.

1. **Actions:**  I have some code which checks if a number between 0-7 has been entered in any of the week number input fields:

  ```
  $('.kn-input-number:contains("Week") .input').on("blur", function () { //instant validation for days per week
        $(this).removeClass("inputInvalid"); //set border back to default
        var value = $(this).val();
        if (value < 0 || value > 7) { //invalid num weeks
            $(this).addClass("inputInvalid"); //if invalid display error msg & style input
            showNotification($(this).parent(),"Enter a number between 0 - 7", "var(--amberAlert)","ca-notification ca-inputNotifcation", 3000);
        }
    });
```

If an invalid number is found an error message is displayed:

![Screen Shot 2023-06-22 at 13 08 13](https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/2a38c219-e903-447d-9ddd-328a43f8e4f2)

2. **The problem** is the on blur event isn't triggering when this form is opened in modal. If however I open this form not in a modal the on blur works as expected.

3. I'd expect the validation to work when opened in a modal. I did some testing on different fields (on different pages) using on blur/change/focus and hit the same issue, the issue only arises if the field is kn-number input.

Let me know if need any other info.

Thanks
Amanda

**Comment by cortexrd** [comment]
Amanda,

I think I found the problem, but not sure.

Can you try in Dev mode to change function **convertNumToTel** by commenting the line:
`$('#' + viewId + ' #' + fieldId).clone().attr('type', 'tel').insertAfter($('#' + viewId + ' #' + fieldId)).prev().remove();`

But still, I don't understand how the modal page could have any effect on the blur event.

BTW, one question: don't you prefer to have the validation be done in real-time as you type, instead of _after_ you move your focus?

Norm

**Comment by CSWinnall** [comment]
Hi Norm,

Yes, commenting out the said line of code does fix the issue. The modal thing is a bit odd and not something I can get my head around.

As for validation, yes sometimes, we've yet to do any real-time validation on our app.

Thanks
Amanda

**Comment by CSWinnall** [comment]
Hi Norm,

Having considered it further yes real-time validation would be better, as user would still be in the input, rather than finding out after they've left. Makes sense.

Amanda

**Comment by cortexrd** [comment]
Amanda,

The problem is due to the fact that I replace the original input field by a copy that has the **tel** type, for added benefits.  But doing so, we lose some events like blur for some reason.

So I've added a new flag that disables the conversion from **numeric** to **tel** type. This should solve your problem.

```
ktl.fields.setCfg({
    convertNumToTel: false,
})
```

There's another way to do the same thing, but on a per-scene basis.  Setting the array **textAsNumericExcludeScenes**.  In that case, you leave the global flag as true and use this in your code, for example:

```
ktl.fields.setCfg({
    textAsNumericExcludeScenes: ['scene_123'],
})
```

> Having considered it further yes real-time validation would be better, as user would still be in the input, rather than finding out after they've left. Makes sense.

I prefer that too.

Norm

**Comment by amandajane-mo** [comment]
Hi Norm,

I've tried the first method in dev (having pulled from git) and it didn't work. I did however get the following error, from the `ktlProcessKeywords` function. :

<img width="1257" alt="Screen Shot 2023-06-24 at 19 41 53" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/79783211/e912b447-a241-4cb2-bc73-730a1423937f">



The keyword _vmxw still worked as expected. The odd thing is when I added the keyword onto the view in the debug area the error didn't occur. Though on other pages where we use _vmxw the error did occur. 

I then thought I'll try your fix in prod mode, using **KTL ver 0.13.8**, I added the code:

```
ktl.fields.setCfg({
    convertNumToTel: false,
});
```

No error occurred and the **fix didn't work**. 

I then tried your second option:

```
 ktl.fields.setCfg({
     textAsNumericExcludeScenes: ['scene_1264'],
 });
```

**Which did work** - hooray! (the second fix worked in dev as well, regardless of the error)

Hope that all makes some sort of sense to you.

Thanks for the fix, just not sure why we're hitting this issue in dev mode?

Amanda

**Comment by cortexrd** [comment]
I think it's due to a missed update in my behalf.
All in sync now, please try again and let me know how it goes.

Norm

**Comment by CSWinnall** [comment]
Hi Norm

The issue with _vmxw is still occurring.  The NumtoTel issue is fixed.

https://arcproject.knack.com/arc-beta#debug/

Craig

**Comment by CSWinnall** [comment]
Hi Norm

I've found the error.  Add this line of code to the processViewKeywords:

`if (keywords && !$.isEmptyObject(keywords)) {`

Which was causing the issue.

Craig

**Comment by amandajane-mo** [comment]
All issues resolved

Nice work Norm
