### ISSUE TITLE
Filter button not working on Android device

### ISSUE THREAD

**Issue by Deanobeano2** [cortexrd/Knack-Toolkit-Library#60]
I've just re-created a filter button, I've successfully used on my Windows and Linux PCs, on my Android phone and it creates the button but when pushed it doesn't pass the "stored" filter parameters to filter the grid.

A long press of the button brings up the Delete/Rename option but nothing happens when pressing either option.

**Comment by cortexrd** [comment]
Hi Dean,

The Android support of drag'n drop has been fixed.  Can you test it please?

Norm

**Comment by Deanobeano2** [comment]
Hi Norm

 

It’s now working as expected.

 

Thank you for the prompt fix.

 

Kind regards

Dean Morrison

General Manager
Excell Cleaning Services Limited
