### ISSUE TITLE
KTL-Toolkit Version Info Bar Positioning Issue

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#61]
I found another minor issue with the Toolkit button not staying in position:

https://vimeo.com/839091757/d2488f4364

Dean

**Comment by cortexrd** [comment]
Hi Dean,

Can you **manually** set your KTL version to **0.13.8** to see if it fixes the bug please?

Norm

**Comment by cortexrd** [comment]
Dean, I took the liberty to change your issue title a bit.
You are actually referring to what is called the **Version Info Bar**.

Closing this issue now, thanks for reporting.

Norm
