### ISSUE TITLE
Using ktlRoles with _ni 

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#63]
Hi Norm,

We're trying to use your **_ni** keyword alongside your **ktlRoles** feature. Our aim is to turn off inline editing for certain user roles.

We've tried:

`_ni=[House & Room, Licence Start Date], [ktlRoles, WH Support Worker, Support Worker]`

What we're trying to achieve is to turn off inline editing for House & Room and Licence Start Date for the aforementioned user roles. This doesn't work.

My question is does ktlRoles work with _ni? If so, what are we doing wrong? If not, this would be a great addition to the ktl.

Thanks
Amanda

**Comment by cortexrd** [comment]
The ktlRoles option wasn't implemented in the _ni keyword, but has been added a minute ago... just for you!

Also, I've added it to a bunch of others, that I thought would be useful.
To find all keywords supported, search in KTL.js for this:

`ktl.core.processKeywordOptions`

Enjoy,
Norm

**Comment by CSWinnall** [comment]
Thank you Norm excellent

**Comment by cortexrd** [comment]
Fix can be found in **0.13.9**.

**Comment by CSWinnall** [comment]
> The ktlRoles option wasn't implemented in the _ni keyword, but has been added a minute ago... just for you!
> 
> Also, I've added it to a bunch of others, that I thought would be useful.
> To find all keywords supported, search in KTL.js for this:
> 
> `ktl.core.processKeywordOptions`
> 
> Enjoy,
> Norm
> 

Hi Norm

Could I ask you to add it to _hc as well.

Thank you
Craig

**Comment by cortexrd** [comment]
Done!  I've added the ktlRoles for both the **_hc** and **_rc** keywords.

Also, I've fixed the ktlRoles option.  It should properly exclude roles now.  I'd ask you to test as many of your use cases as possible please.

Norm

**Comment by cortexrd** [comment]
When you refresh your browser, use the Ctrl+F5 to bypass the cache. I think this is why we had some recurring issues yesterday.  Sometimes, I release beta code under the same file name (ex: KTL-0.13.8.js) and your browser doesn't see the change due to caching.

I do this to do quick re-releases until I get the final version.

Norm

**Comment by amandajane-mo** [comment]
This is excellent Norm, we have lots of use cases for _hc and _rc with ktlRoles. So we can test the hell out of it.

We'll report back

Thanks
Amanda

**Comment by CSWinnall** [comment]
> Done! I've added the ktlRoles for both the **_hc** and **_rc** keywords.
> 
> Also, I've fixed the ktlRoles option. It should properly exclude roles now. I'd ask you to test as many of your use cases as possible please.
> 
> Norm

Hi Norm 

We can't see the update for the ktlRoles on the _hc or _rc keyword yet.

Craig

**Comment by cortexrd** [comment]
Sorry, you're right.  I forgot to push the prod branch!
It's done now, give it a try.

Norm

**Comment by CSWinnall** [comment]
> Sorry, you're right.  I forgot to push the prod branch!
> It's done now, give it a try.
> 
> Norm

Hi Norm

We got the new update. However the ktlRoles isn't  working with the hc and rc and it broke our new field keyword as you changed the name of one of your functions.  I'm getting better at spotting these and fixing them.

If possible we could really do with a heads up if you change function names, especially if you change them without updating the version number.

I'm thinking that we are pushing updates too quick as we are excited about new features and we possibly need to have a version behind on our live app.

Craig

**Comment by amandajane-mo** [comment]
Hi Norm

When you add ktlRoles to ni it worked but it seems to have stopped working.  This is the string we are using:

_ni=[House & Room, Licence Start Date], [ktlRoles, WH Support Worker, Support Worker]

Any ideas

**Comment by cortexrd** [comment]
If you type in the console:

`ktlkw('_ni');`

Does it show you the right parameters and options?  I thought the ampersand "&" character could cause a problem, but here all looks good when I try your string.

Also, I have a similar string in my Tutorial App and it works okay.

`_ni=[Phone, Membership], [ktlRoles, Tutorials]`

It disabled inline editing for the two columns when the role contains Tutorials.

So I wonder what happens on your side...
Do you have more details?

Norm
