### ISSUE TITLE
_uvc Keyword not working with non-text fields

### ISSUE THREAD

**Issue by Greenlight88** [cortexrd/Knack-Toolkit-Library#64]
Hi Norm, 

As discussed on the forum am having trouble getting the _uvc keyword to work with non-text fields such as 

Name
Email
Address

People out there might also like to use

Phone
Link

though personally the first set would be more than fine.

Now I'm a non-coder so potentially I just need to input the parameters in a certain way. Or maybe it was only designed to work with text fields - either way I think it would be greatly enhanced to just work with these other fields with out any special form of expression

Use case is probably obvious but we would use it to uniquely identify clients on our system and prevent duplicates there. Very difficult to achieve this natively 

Also, I have successfully used the _uvc keyword for text fields so am confident its not my set up - it draws in a blank value whenever the field has sub-fields and otherwise works

Thanks as always Norm - I have subscribed to the changelog as you suggested

**Comment by cortexrd** [comment]
Hi Michael,

I've upgraded the **_uvc** keyword to support **Name**, **Address**, **Phone** and **Link** field types.

**Email** is not required because Knack automatically enforces unique emails by default.

You can test it out now in **KTL v0.13.10**.

Enjoy,
Norm
