### ISSUE TITLE
Reuse Last Source button 

### ISSUE THREAD

**Issue by KYLumber** [cortexrd/Knack-Toolkit-Library#66]
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/80362514/0cf8e5fe-c196-430a-baa4-641b69638715)
Noticed a button issue where the “Reuse Last Source” sits overtop of the search “Reset” button. The search reset button only appears after a search is conducted so the button needs to shift position when this condition exists.

**Comment by cortexrd** [comment]
Sean,

I can't reproduce your layout and the bug in my apps.  I see that in your example, the Reset button has a **blue color**.  Here, all I have is the **text link**, not a button with the color.

This seems like a CSS-related issue, where some custom code could conflict with the KTL's.

If you have some additional information about your Live App Design page settings and your CSS file content, it would help.

Norm

**Comment by KYLumber** [comment]
I did notice that this only happens when the browser window is made narrower than full screen.  I can manipulate the button placement by dragging the browser width.

Dragged wider
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/80362514/2f9cb3cc-d191-4b96-9cc0-f8ab1f6f9ea1)

Same browser tab, no change other than browser width.
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/80362514/888111e6-6943-47c9-8632-66ddb30f8ba2)

If I drag it very narrow the "Use Last Source" option actually falls below the existing buttons.
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/80362514/e813a3a8-bcb9-49cc-b368-de3f59c51245)

You also mentioned CSS related issue.  Diving through my app CSS I think the only section related to this would be:

/* Button Modifications */
  /* sets the general formatting of buttons */
  .kn-button, .fc-button {
    color: white !important;
    background-color: #062845 !important;
    font-size: 1em !important;
    transition-duration: 0.4s;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }  

  /* this changes the button when hovering over */
  .kn-button:hover, .fc-button:hover {
    background-color: #DFE8F4 !important; 
    color: black !important;
  }
  /* depresses a button when clicked */
  .kn-button:active, .fc-button:active {
    box-shadow: 0 1px black;
    transform: translateY(2px);
  }

**Comment by cortexrd** [comment]
Hi Sean,

The bug has been fixed. Can you test please?

Thanks for reporting,
Norm
