### ISSUE TITLE
New NodeJS_FileServer.js

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#69]
Hi Norm

I pulled the lates from GitHub and when I start the server, I get a path issue. It is directing to the wrong path.
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/c622eb51-eff1-4e5b-b04e-505254a232f1)

Craig

**Comment by CharlesBrunelleIO** [comment]
Hi Craig,
We removed the hardcoded path of `c:/code` from the bash script to better match the [Wiki](https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Advanced-Development-Modes#cloning-the-source-code).

2 solutions for you: 

1. Call the NodeJS_FileServer.js script with an absolute path via command line.
 `node NodeJS_FileServer.js <path to your root>`
2. Move your Ktl folder to `<your root>/Lib/Ktl`. The default path will do the rest.

Charles

**Comment by cortexrd** [comment]
Thank you Charles for handling this.  You path optional parameter was very useful.
Craig seems happy with the solution.
Closing issues now.

Norm

**Comment by cortexrd** [comment]
BTW, Craig was running the script from VS Code.  That's why his default path wasn't the right one.

**Comment by CSWinnall** [comment]
Hi Charles

This seems like a step backwards to me where before it used a relative path
I now need an absolute.  As Norm has said I'm happy with his solution I
feel this is one extra step that some people will get stuck on. Especially
as your NodeJS_FileServer file is within the KTL folder.  Very confusing.

Kind regards,

Craig Winnall
07543423538

**Comment by CSWinnall** [comment]
Just as an aside my partner Amanda uses a Mac so she has no choice but to
use vsCode to run the file as she can run a .bat again this is just an
extra step she has to do to run the server.

Craig

**Comment by CharlesBrunelleIO** [comment]
Hi Craig,

This is not a step backward. Sorry, I added a bit of confusion there. You definitely can use a relative path, but it will depend on where you execute the script.

I use a Mac without any issues. You just use a terminal to run `node ./NodeJS/NodeJS_FileServer.js` from your KTL project's root with a path (relative or absolute) or without a path if you followed the Wiki.

BR,
Charles

**Comment by CSWinnall** [comment]
> Hi Craig,
> 
> This is not a step backward. Sorry, I added a bit of confusion there. You definitely can use a relative path, but it will depend on where you execute the script.
> 
> I use a Mac without any issues. You just use a terminal to run `node ./NodeJS/No
deJS_FileServer.js` from your KTL project's root with a path (relative or absolute) or without a path if you followed the Wiki.
> 
> BR,
> Charles

Ok.
