### ISSUE TITLE
"Updating to new version" constant refresh

### ISSUE THREAD

**Issue by hwrainbird** [cortexrd/Knack-Toolkit-Library#72]
I've had to disable the KTL on a few of my apps because the app is refreshing repeatedly with the message "Updating to new version..". I've managed to prevent this from happening by going to the Sysop Dashboard and manually changing the Value to match the KTL Version in the top right and then clicking Broadcast Now.

Any help would be much appreciated.

**Comment by cortexrd** [comment]
Hi,

You've done the right thing to stop the looping.

Now, I've seen this a few times, and would really like to solve this issue.  I am trying to figure out what triggers this looping.  So I'd need more information on the sequence of events, or the system status when this was observed.

Can we have a live conversation?  Teams, Zoom, Phone, other?
Send me an email at nd@ctrnd.com

Norm
