### ISSUE TITLE
Issue using Dev Mode

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#8]
Hi [@NormandDefayette_CortexRD](https://forums.knack.com/u/normanddefayette_cortexrd)
We really want to use your ktl and have got the basic version running fine.

I’m struggling to get your developer mode working. Out of all your amazing features this is one that we would really like to test. This is the first Knack app that we have developed. We have a fairly good understanding of how Knack works and have a lot of custom JS code which we call from an online server.

I have tried to follow your setup in the readme file. We get as far as downloading your code and running the nodeJS server. Then we load our App up with the 5 lines of loader code. The server then says missing files and lists these
appname.js, ktl.js, ktl.css

We would really appreciate any help you can give us. We just feel like we are missing a step somewhere.

Craig

**Comment by cortexrd** [comment]
Finally it was more of a documentation issue.  I will clarify the procedure.

Shall I close this one?

Norm
