### ISSUE TITLE
_hf=fieldName1, fieldName2 hiding data but not the label

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#80]
I am using the hide field feature in a form and it is not hiding fields. I have 3 fields and all three remain on the form. The form is in a modal popup but it persisted even when I removed the modal setting.

<img width="543" alt="image" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/87c28d3f-3638-467a-b634-b8846b62a2eb">

**Comment by djbbiz** [comment]
I found the issue, the keyword is only working with the fieldID not the name, so this works:
_hf=field_348, field_349, field_245

**Comment by cortexrd** [comment]
Hi Dean,

I can't reproduce the problem.  I tried both Add and Update forms, with and without read-only fields, modal and non-modal...  _hf always work with the field label and field ID.

Can you give me the URL of a page (for debugging) where the bug happens please?

Norm

**Comment by cortexrd** [comment]
Dean,

I see something in your screen shot that seems wrong.

Your keyword goes like this:
**_hf=GHL TaskID, LocationID Webhook, GHL ContactID**

it should be:
**_hf=TaskID, LocationID, ContactID** 
The text in the keyword must match the view's, exactly.
I think you may have used the "original" text from the field name in the table view.

Can you try this please?

Norm

**Comment by djbbiz** [comment]
You are correct Norm, I thought it needed the actual Field Name and not the shortened Label.  The Wiki docs state that the use is:
_hf=fieldName1, fieldName2

So I was confused as I believe a fieldName as defined in Knack is different than the Field Label that is actually being used on a View. And now that you mention it, I realized that Grids work the same way with the Column Label not the actual fieldName. 

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/4ca4ecd2-387b-47e2-8037-4a7866448c33)


It might be of use to add some clarification in the docs about that.

**Comment by cortexrd** [comment]
You're right Dean.  The names and labels are the same by default.  If you change a field's name, the labels will follow in all views.  But as we know, it's possible to change the label in a specific view to shorten it for example.  The label then becomes "decoupled" from the name.  This means that if you change that field's name, this changed label will remain the same, and will not follow anymore.

So I've updated the documentation to make this clearer.

In general in the KTL's new philosophy, the Universal Selector find its element using either:
1) the field ID or field label in the view
2) the view ID or the view title.

Thanks for reporting,
Norm
