### ISSUE TITLE
Blue Text

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#9]
Hi
All our text on details and grid view has turned blue.
Is this intentional?
If so how can we turn this off?
It looks like this is an added inline style.

Craig

**Comment by cortexrd** [comment]
I just fixed the problem.
Please refresh your app and you should have normal black text in the tables.
BTW, that blue color is Knack's default for **links** in all new apps, so you'll still see that for links.

**Comment by CSWinnall** [comment]
I'll look at this this evening.
Thank you
