### ISSUE TITLE
Header Alignment

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#91]
Hi Norm 
I have added the keyword _ha to a table and the headers are not aligning.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/df034ab5-5abb-4296-af08-12a01a61f31e)

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/34d02073-4d6f-4bb2-adb0-765a4135f385)

Craig

**Comment by cortexrd** [comment]
Craig,

Can you try with regular text headers, without HTML like line breaks?
I thought that the <br /> could be the culprit, but I just tried it and if works in my Tutorial app.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/74d5a244-d8f6-42e9-a75a-2e6eaffc0861)

Can you please reproduce the problem in your debug copy, in that page I can access here:
https://arcproject.knack.com/arc-beta#inductiontreatment/treatment/

Just add the **_ha** keyword in the top table (view_2887) and set a few columns to centered and right-aligned.

Norm

**Comment by cortexrd** [comment]
And don't forget to update all your jQueries to the new syntax!  

#selector    becomes ->  $('#selector')

**Comment by CSWinnall** [comment]
Hi Norm

The HTML was my initial thought too, but I tried it without, and it still wasn't working.
I will setup the area for you and let you know when it's ready.

We are waiting on a version bump before we update our prod KTL so that's why we haven't fixed the JQuery selectors yet.

Craig

**Comment by CSWinnall** [comment]
Ok I.ve added the ha and made 2 columns centre aligned.

Craig

**Comment by cortexrd** [comment]
The reason is a bad default init of the **headerAlignment** flag.

I've changed it to true and it will applied in next release.

In the meantime, you can manually enable it with this in your own init:

```
ktl.views.setCfg({
    headerAlignment: true,
})
```

Norm

**Comment by CSWinnall** [comment]
So, an odd thing.  I haven't pulled any new code, but the header alignment flag works on 15.7 but not on 15.3. 

So this will be fixed when we update our prod code we are just waiting for a version bump to 15.8.

**Comment by regnerps** [comment]
Can we align the grid with a vertical centering?  When the grid height grows the content of each field is aligned at the top.

**Comment by cortexrd** [comment]
Currently, the KTL doesn't support that.

But you can easily do it in your CSS editor in the Builder by adding this line:

```
.kn-content table td, .kn-content table th {
	vertical-align: middle;
}
```

This will center all tables' cells and headers vertically.

If you want only the cells, not the headers:

```
.kn-content table td {
	vertical-align: middle;
}
```

Hope this helps,
Norm
