### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#95]
Hi Norm

Just a minor issue but it may be an idea to let users set KTL's Date format as we in the UK use dd/mm/yyyy.  I am aware that I can manipulate the date object just thought this may be a good cfg flag.

Craig

**Comment by cortexrd** [comment]
Hi Craig,

Actually, the users shouldn't have to set up anything since the KTL is aware of each date field format.  It should just respect that format.

Do you have a specific use case or keyword to mention?  I can think of **_lud** (last updated date) as of today, that could cause problems.

Norm

**Comment by CSWinnall** [comment]
That's great if it's already covered we just had a thought about it the
other day.

No use case yet however when we start switching over to _lud  will that be
an issue.

Also when I was trying out the logs you specified that the date fields had
to be a certain format in the wiki mm/dd/yyyy is that still the case?  We
will be setting that up within the next month so would be good to know.

Craig

**Comment by CharlesBrunelleIO** [comment]
Hi Craig,
I opened a Pull Request for _lud to support dd/mm/yyyy. 
Charles

**Comment by cortexrd** [comment]
Craig,

I've just released KTL v0.15.12 with the _lud fix.

About the Account Logging date format concern, you're right.  We'll definitely need to address this compatibility issue and update the documentation.  In no way the user should be imposed any format.  The code should always automatically detect the existing format and adapt itself.

If you want to start using the Account Logging feature now, you can still do it as long as you follow the format specified in the Wiki.  Eventually, you'll be able to update to dd/mm/yyyy when the code is ready.

Norm

**Comment by CSWinnall** [comment]
Great thank you Norm
