### ISSUE TITLE
_lud reversing dd/mm/yyyy to mm/dd/yyyy

### ISSUE THREAD

**Issue by MickGraham23** [cortexrd/Knack-Toolkit-Library#98]
Hi, I maybe have more than 1 issue but here goes.

I have my date format set for dd/mm/yy and in some instances it works fine ?
However on another table/grid it reverts the date to mm/dd/yyyy.

I had a theory that it was because I have a page with multiple grids.  It looks like the first grid works but then the next one does the reversing, but Im still trying to suss it out??

... follow up..

I now have 1 grid that doesnt show any changes at all when I grid edit, apart from changing the field that I have edited.
The second one, just reverts the dates.

**Comment by MickGraham23** [comment]
This problem still exists.  LUD dates are always reversed on my Grid Table.   This makes it non useable because some of my tables are set to display today only.

**Comment by CharlesBrunelleIO** [comment]
Hi Mick,

I'm opening a Pull Request to fix this bug.

Charles

**Comment by CharlesBrunelleIO** [comment]
Hi Micheal,
Meanwhile, the KTL _lud only supports mm/dd/yyyy. You can use this format until my PR is merged.
Charles

**Comment by cortexrd** [comment]
Mike,

I've updated the KTL to v0.15.12, and you fix is included in there.
Can you test it please and let me know if all is ok now?

Norm

**Comment by MickGraham23** [comment]
Hi Norm, Thanks for that. Do I need to do anything bro update the loader first?Regards Michael On 12 Sept 2023 21:51, "Cortex R&D Inc." ***@***.***> wrote:
Mike,
I've updated the KTL to v0.15.12, and you fix is included in there.
Can you test it please and let me know if all is ok now?
Norm

**Comment by MickGraham23** [comment]
Hi Norm

It still shows as v0.15.11 but it is working perfectly.
Additionally the other issue I had reported about the WhatsApp coded has been resolved too.

Thanks so very much.   The KTL is a fantastic tool 😊

Rgds
Mick

Sent from Mail for Windows

**Comment by cortexrd** [comment]
> Hi Norm It still shows as v0.15.11 but it is working perfectly. 

Your fix was probably introduced in 0.15.11.
About the version, try a **full refresh** to bypass your cache:  Ctrl+F5. You should now see 0.15.12.  

> Additionally the other issue I had reported about the WhatsApp coded has been resolved too.

This is weird, since we didn't change anything that's related to that.

> Thanks so very much. The KTL is a fantastic tool 😊 Rgds Mick

Wow, I'm so happy to read that!  Thank you for reporting the bugs and helping us improving it.

Norm
