### ISSUE TITLE
Linked Filters (_lf) not working

### ISSUE THREAD

**Issue by godfredbrown** [cortexrd/Knack-Toolkit-Library#99]
Hello, I tried applying the lf feature on the main graph but the other graphs do not show.
Is there something I need to turn off?
This is the code I am using:

KnackInitAsync = function ($, callback) { // Load the Knack Toolkit Library (KTL)
    (window.LazyLoad = LazyLoad) && LazyLoad.js(['https://ctrnd.s3.amazonaws.com/Lib/KTL/KTL_Start.js'], () => {
        loadKtl($, callback, (typeof KnackApp === 'function' ? KnackApp : null), '' /*KTL version, leave blank to get latest*/, 'min'/*min or full*/);
    })
};

//This file is a template that shows how to customize the KTL for your application.
//Insert the code below in the Javascript pane of your app's Builder, just after the loader code.
//Once the KTL is done loading, it will jump in the ktlReady function and apply your desired settings.
//All code must be located inside the ktlReady section.
//See GitHub's Wiki for more details.

//Your app's version.
window.APP_VERSION = '1.0.0';

window.ktlReady = function (appInfo = {}) {
    var ktl = new Ktl($, appInfo);

    //KTL Setup - BEGIN
    ktl.scenes.setCfg({
        //versionDisplayName: '', //Short version of your app name. Leave empty to hide it. Comment whole line for actual app name.
    })

    ktl.core.setCfg({
        developerNames: ['Firstname Lastname'], //Add your name here to get super powers!

        //Main KTL feature switches.  Here is where your App can override the defaults and enable/disable the features.
        enabled: {
            //"Basic" features
            //Enabled by default. To disable them, their flag must exist and be set to false.
            versionInfo: {
                viShowAppInfo: false,
                viShowKtlInfo: false,
                viShowToRoles: ['Developer'], //Array of Account Roles strings who can see the version info bar. Leave empty for all.
                viPosX: 'right', //right, center, left
                viPosY: 'top', //top, bottom
                viPosXMobile: 'center', //right, center, left
                viPosYMobile: 'bottom', //top, bottom
                viOpacity: 50, //0 to 100
                viOpacityHover: 100, //0 to 100
            },

            showMenuInTitle: false,
            selTextOnFocus: false,
            inlineEditColor: false,
            rowHoverHighlight: false,
            chznBetter: false,
            autoFocus: false,
            sortedMenus: false,
            userFilters: false,
            persistentForm: false,
            calendarGotoDate: false,
            rememberMe: false,
            formPreValidation: false,
            spinnerWatchDog: false,
            idleWatchDog: false,
            debugWnd: false,
        },
    })
    //KTL Setup - END

    //KTL callbacks to your App - BEGIN
    //KTL callbacks to your App - END

    /////////////////////////////////////////////////
    //Your App-specific code goes here...
}

**Comment by CharlesBrunelleIO** [comment]
Hi,

You need to enable User Filters for this to work in your config `userFilters: true,`. 

Charles

**Comment by godfredbrown** [comment]
Thank you for your response Charles.
I will apply that.

Best regards,
Godfred Brown

**Comment by CharlesBrunelleIO** [comment]
No problem. 

I will open a Pull request soon because it shouldn't depend on `userFilters`.  Afterward, you won't need to enable this for _lf to work.

Charles

**Comment by cortexrd** [comment]
Godfred,

Can you test the latest release v0.15.12 please?  Press Ctrl+F5 to do a full refresh.

Norm
